### ISSUE TITLE
Xiaomi Mi8 with MIU 11 - Crash Tagmo 

### ISSUE THREAD

**Issue by Zullivan1987** [HiddenRamblings/TagMo#157]
My logcat
https://drive.google.com/open?id=1zneF_LQgQQ8JMfSpFUXXkNXBdM680uydJoD5btYVrwk

java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeLo(TimSort.java:777)
	at java.util.TimSort.mergeAt(TimSort.java:514)
	at java.util.TimSort.mergeCollapse(TimSort.java:441)
	at java.util.TimSort.sort(TimSort.java:245)
	at java.util.Arrays.sort(Arrays.java:1498)
	at java.util.ArrayList.sort(ArrayList.java:1470)
	at java.util.Collections.sort(Collections.java:201)
	at com.hiddenramblings.tagmo.BrowserAmiibosAdapter$AmiiboFilter.publishResults(BrowserAmiibosAdapter.java:327)
	at android.widget.Filter$ResultsHandler.handleMessage(Unknown Source:10)
	at android.os.Handler.dispatchMessage(Unknown Source:21)
	at android.os.Looper.loop(Unknown Source:207)
	at android.app.ActivityThread.main(Unknown Source:107)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:274)

**Comment by AbandonedCart** [comment]
This code has been completely revised and should now function correctly. Please comment back if the error was not solved to open this issue again.
