### ISSUE TITLE
Attempting to use the update function causes a crash

### ISSUE THREAD

**Issue by L31FY** [HiddenRamblings/TagMo#332]
Removed to protect privacy.

```
11-06 19:46:19.905  6266  6286 E ramblings.tagm: Invalid ID 0x00000000.
11-06 19:46:19.905  6266  6286 W ResourcesOffloading: An exception occurred : 
11-06 19:46:19.905  6266  6286 W ResourcesOffloading: android.content.res.Resources$NotFoundException: Resource ID #0x0
11-06 19:46:19.905  6266  6286 W ResourcesOffloading: 	at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:249)
11-06 19:46:19.905  6266  6286 W ResourcesOffloading: 	at android.content.res.Resources.offloadDrawable(Resources.java:2826)
11-06 19:46:19.905  6266  6286 W ResourcesOffloading: 	at android.app.ResourcesOffloading$ResourcesOffloadingRunnable.run(ResourcesOffloading.java:82)
11-06 19:46:19.905  6266  6286 W ResourcesOffloading: 	at java.lang.Thread.run(Thread.java:920)
```

```
11-06 19:47:34.493  6266  6266 E AndroidRuntime: FATAL EXCEPTION: main
11-06 19:47:34.493  6266  6266 E AndroidRuntime: Process: com.hiddenramblings.tagmo, PID: 6266
11-06 19:47:34.493  6266  6266 E AndroidRuntime: java.lang.IllegalArgumentException: Comparison method violates its general contract!
11-06 19:47:34.493  6266  6266 E AndroidRuntime: 	at java.util.TimSort.mergeLo(TimSort.java:777)
11-06 19:47:34.493  6266  6266 E AndroidRuntime: 	at java.util.TimSort.mergeAt(TimSort.java:514)
11-06 19:47:34.493  6266  6266 E AndroidRuntime: 	at java.util.TimSort.mergeCollapse(TimSort.java:441)
11-06 19:47:34.493  6266  6266 E AndroidRuntime: 	at java.util.TimSort.sort(TimSort.java:245)
11-06 19:47:34.493  6266  6266 E AndroidRuntime: 	at java.util.Arrays.sort(Arrays.java:1492)
11-06 19:47:34.493  6266  6266 E AndroidRuntime: 	at java.util.ArrayList.sort(ArrayList.java:1470)
11-06 19:47:34.493  6266  6266 E AndroidRuntime: 	at java.util.Collections.sort(Collections.java:206)
11-06 19:47:34.493  6266  6266 E AndroidRuntime: 	at p3.d$b.publishResults(Unknown Source:11)
11-06 19:47:34.493  6266  6266 E AndroidRuntime: 	at android.widget.Filter$ResultsHandler.handleMessage(Filter.java:284)
11-06 19:47:34.493  6266  6266 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-06 19:47:34.493  6266  6266 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
11-06 19:47:34.493  6266  6266 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
11-06 19:47:34.493  6266  6266 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8582)
11-06 19:47:34.493  6266  6266 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-06 19:47:34.493  6266  6266 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:563)
11-06 19:47:34.493  6266  6266 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
```

**Comment by AbandonedCart** [comment]
I grabbed the log and removed the content for your privacy. The log is only supposed to pick up "TagMo" content, but sometimes includes NFC data that I prefer to filter out just in case.

**Comment by AbandonedCart** [comment]
The good news is that one of the issues was recently solved. The bad news is that the update issue doesn't appear to be included in the logs. There have been some improvements to that, though, that may have fixed it. You may have to perform a manual update to jump-start the fix. Give me a minute to look into that first error, though. That is one I haven't seen before.

**Comment by L31FY** [comment]
That is a more than acceptable fix. I hate to keep blaming it, but it's not completely unlikely that Android 12 Beta over here has a relationship with it. I've had more breakage and outright strange issues with everything.

**Comment by AbandonedCart** [comment]
They changed a lot and the new Android Emulator requires upgrading to a Mac version that is equally broken, so it's been a struggle to debug Android 12.
