### ISSUE TITLE
Instant Crash, Google Pixel 6 Pro

### ISSUE THREAD

**Issue by Tiberon** [HiddenRamblings/TagMo#379]
Just installed the latest release of TagMo 2.7.8, but crashes on my Pixel 6 Pro.

Logcat below
---------------------------------

Google Pixel 6 Pro
Android SDK 31 (12)
TagMo 7b60375

--------- beginning of crash
12-20 14:01:41.446 30830 30830 E AndroidRuntime: FATAL EXCEPTION: main
12-20 14:01:41.446 30830 30830 E AndroidRuntime: Process: com.hiddenramblings.tagmo, PID: 30830
12-20 14:01:41.446 30830 30830 E AndroidRuntime: java.lang.IllegalStateException: Fragment SettingsFragment_{c3d680} (389e4186-a482-4f71-8441-52fb46916e89 id=0x7f090165) not attached to a context.
12-20 14:01:41.446 30830 30830 E AndroidRuntime: 	at androidx.fragment.app.Fragment.requireContext(Fragment.java:900)
12-20 14:01:41.446 30830 30830 E AndroidRuntime: 	at androidx.fragment.app.Fragment.getResources(Fragment.java:964)
12-20 14:01:41.446 30830 30830 E AndroidRuntime: 	at androidx.fragment.app.Fragment.getString(Fragment.java:986)
12-20 14:01:41.446 30830 30830 E AndroidRuntime: 	at com.hiddenramblings.tagmo.settings.SettingsFragment.onKeysClicked(SettingsFragment.java:163)
12-20 14:01:41.446 30830 30830 E AndroidRuntime: 	at com.hiddenramblings.tagmo.BrowserActivity.lambda$showSetupSnackbar$21$com-hiddenramblings-tagmo-BrowserActivity(BrowserActivity.java:1737)
12-20 14:01:41.446 30830 30830 E AndroidRuntime: 	at com.hiddenramblings.tagmo.BrowserActivity$$ExternalSyntheticLambda24.onClick(Unknown Source:4)
12-20 14:01:41.446 30830 30830 E AndroidRuntime: 	at com.google.android.material.snackbar.Snackbar$1.onClick(Snackbar.java:351)
12-20 14:01:41.446 30830 30830 E AndroidRuntime: 	at android.view.View.performClick(View.java:7441)
12-20 14:01:41.446 30830 30830 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7418)
12-20 14:01:41.446 30830 30830 E AndroidRuntime: 	at android.view.View.access$3700(View.java:835)
12-20 14:01:41.446 30830 30830 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:28676)
12-20 14:01:41.446 30830 30830 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
12-20 14:01:41.446 30830 30830 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-20 14:01:41.446 30830 30830 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
12-20 14:01:41.446 30830 30830 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
12-20 14:01:41.446 30830 30830 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7839)
12-20 14:01:41.446 30830 30830 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-20 14:01:41.446 30830 30830 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
12-20 14:01:41.446 30830 30830 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
12-20 14:02:17.653 31240 31296 E AndroidRuntime: FATAL EXCEPTION: pool-4-thread-1
12-20 14:02:17.653 31240 31296 E AndroidRuntime: Process: com.hiddenramblings.tagmo, PID: 31240
12-20 14:02:17.653 31240 31296 E AndroidRuntime: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
12-20 14:02:17.653 31240 31296 E AndroidRuntime: 	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:9316)
12-20 14:02:17.653 31240 31296 E AndroidRuntime: 	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1772)
12-20 14:02:17.653 31240 31296 E AndroidRuntime: 	at android.view.View.requestLayout(View.java:25697)
12-20 14:02:17.653 31240 31296 E AndroidRuntime: 	at android.view.View.requestLayout(View.java:25697)
12-20 14:02:17.653 31240 31296 E AndroidRuntime: 	at android.view.View.requestLayout(View.java:25697)
12-20 14:02:17.653 31240 31296 E AndroidRuntime: 	at android.view.View.requestLayout(View.java:25697)
12-20 14:02:17.653 31240 31296 E AndroidRuntime: 	at android.view.View.requestLayout(View.java:25697)
12-20 14:02:17.653 31240 31296 E AndroidRuntime: 	at android.view.View.requestLayout(View.java:25697)
12-20 14:02:17.653 31240 31296 E AndroidRuntime: 	at android.view.View.requestLayout(View.java:25697)
12-20 14:02:17.653 31240 31296 E AndroidRuntime: 	at android.view.View.setFlags(View.java:16377)
12-20 14:02:17.653 31240 31296 E AndroidRuntime: 	at android.view.View.setVisibility(View.java:11896)
12-20 14:02:17.653 31240 31296 E AndroidRuntime: 	at com.hiddenramblings.tagmo.BrowserActivity.lambda$locateKeyFiles$38$com-hiddenramblings-tagmo-BrowserActivity(BrowserActivity.java:1958)
12-20 14:02:17.653 31240 31296 E AndroidRuntime: 	at com.hiddenramblings.tagmo.BrowserActivity$$ExternalSyntheticLambda25.run(Unknown Source:2)
12-20 14:02:17.653 31240 31296 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-20 14:02:17.653 31240 31296 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-20 14:02:17.653 31240 31296 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:920)
12-20 14:02:19.871 31418 31452 E AndroidRuntime: FATAL EXCEPTION: pool-4-thread-1
12-20 14:02:19.871 31418 31452 E AndroidRuntime: Process: com.hiddenramblings.tagmo, PID: 31418
12-20 14:02:19.871 31418 31452 E AndroidRuntime: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
12-20 14:02:19.871 31418 31452 E AndroidRuntime: 	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:9316)
12-20 14:02:19.871 31418 31452 E AndroidRuntime: 	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1772)
12-20 14:02:19.871 31418 31452 E AndroidRuntime: 	at android.view.View.requestLayout(View.java:25697)
12-20 14:02:19.871 31418 31452 E AndroidRuntime: 	at android.view.View.requestLayout(View.java:25697)
12-20 14:02:19.871 31418 31452 E AndroidRuntime: 	at android.view.View.requestLayout(View.java:25697)
12-20 14:02:19.871 31418 31452 E AndroidRuntime: 	at android.view.View.requestLayout(View.java:25697)
12-20 14:02:19.871 31418 31452 E AndroidRuntime: 	at android.view.View.requestLayout(View.java:25697)
12-20 14:02:19.871 31418 31452 E AndroidRuntime: 	at android.view.View.requestLayout(View.java:25697)
12-20 14:02:19.871 31418 31452 E AndroidRuntime: 	at android.view.View.requestLayout(View.java:25697)
12-20 14:02:19.871 31418 31452 E AndroidRuntime: 	at android.view.View.setFlags(View.java:16377)
12-20 14:02:19.871 31418 31452 E AndroidRuntime: 	at android.view.View.setVisibility(View.java:11896)
12-20 14:02:19.871 31418 31452 E AndroidRuntime: 	at com.hiddenramblings.tagmo.BrowserActivity.lambda$locateKeyFiles$38$com-hiddenramblings-tagmo-BrowserActivity(BrowserActivity.java:1958)
12-20 14:02:19.871 31418 31452 E AndroidRuntime: 	at com.hiddenramblings.tagmo.BrowserActivity$$ExternalSyntheticLambda25.run(Unknown Source:2)
12-20 14:02:19.871 31418 31452 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-20 14:02:19.871 31418 31452 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-20 14:02:19.871 31418 31452 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:920)
--------- beginning of main
12-20 14:07:04.085  3581  3581 I ramblings.tagm: Late-enabling -Xcheck:jni
12-20 14:07:04.203  3581  3581 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10452; state: ENABLED
12-20 14:07:04.286  3581  3581 V GraphicsEnvironment: ANGLE Developer option for 'com.hiddenramblings.tagmo' set to: 'default'
12-20 14:07:04.286  3581  3581 V GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
12-20 14:07:04.286  3581  3581 D NetworkSecurityConfig: No Network Security Config specified, using platform default
12-20 14:07:04.287  3581  3581 D NetworkSecurityConfig: No Network Security Config specified, using platform default
12-20 14:07:04.323  3581  3602 D vulkan  : searching for layers in '/data/app/~~lzEpSX78-FBf70abnCAknQ==/com.hiddenramblings.tagmo-Zao-7QMmgQ7iCTtJqPE--w==/lib/arm64'
12-20 14:07:04.323  3581  3602 D vulkan  : searching for layers in '/data/app/~~lzEpSX78-FBf70abnCAknQ==/com.hiddenramblings.tagmo-Zao-7QMmgQ7iCTtJqPE--w==/base.apk!/lib/arm64-v8a'
12-20 14:07:04.327  3581  3602 D mali_cmarp_predictor: checking cmar_predictor for com.hiddenramblings.tagmo
12-20 14:07:04.388  3581  3581 W ramblings.tagm: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (unsupported, reflection, allowed)
12-20 14:07:04.388  3581  3581 W ramblings.tagm: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (unsupported, reflection, allowed)
12-20 14:07:04.437  3581  3581 D RenderScript HIDL Adaptation: IRenderScriptDevice::getService()
12-20 14:07:04.438  3581  3581 D RenderScript HIDL Adaptation: IRenderScriptDevice::getService() returned 0x0
12-20 14:07:04.438  3581  3581 D RenderScript HIDL Adaptation: Using Fallback Path.
12-20 14:07:04.444  3581  3581 D ramblings.tagm: Successfully queried cache dir: /data/user_de/0/com.hiddenramblings.tagmo/code_cache
12-20 14:07:04.444  3581  3581 D RenderScript: Setting cache dir: /data/user_de/0/com.hiddenramblings.tagmo/code_cache
12-20 14:07:04.883  3581  3633 E AndroidRuntime: FATAL EXCEPTION: pool-4-thread-1
12-20 14:07:04.883  3581  3633 E AndroidRuntime: Process: com.hiddenramblings.tagmo, PID: 3581
12-20 14:07:04.883  3581  3633 E AndroidRuntime: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
12-20 14:07:04.883  3581  3633 E AndroidRuntime: 	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:9316)
12-20 14:07:04.883  3581  3633 E AndroidRuntime: 	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1772)
12-20 14:07:04.883  3581  3633 E AndroidRuntime: 	at android.view.View.requestLayout(View.java:25697)
12-20 14:07:04.883  3581  3633 E AndroidRuntime: 	at android.view.View.requestLayout(View.java:25697)
12-20 14:07:04.883  3581  3633 E AndroidRuntime: 	at android.view.View.requestLayout(View.java:25697)
12-20 14:07:04.883  3581  3633 E AndroidRuntime: 	at android.view.View.requestLayout(View.java:25697)
12-20 14:07:04.883  3581  3633 E AndroidRuntime: 	at android.view.View.requestLayout(View.java:25697)
12-20 14:07:04.883  3581  3633 E AndroidRuntime: 	at android.view.View.requestLayout(View.java:25697)
12-20 14:07:04.883  3581  3633 E AndroidRuntime: 	at android.view.View.requestLayout(View.java:25697)
12-20 14:07:04.883  3581  3633 E AndroidRuntime: 	at android.view.View.setFlags(View.java:16377)
12-20 14:07:04.883  3581  3633 E AndroidRuntime: 	at android.view.View.setVisibility(View.java:11896)
12-20 14:07:04.883  3581  3633 E AndroidRuntime: 	at com.hiddenramblings.tagmo.BrowserActivity.lambda$locateKeyFiles$38$com-hiddenramblings-tagmo-BrowserActivity(BrowserActivity.java:1958)
12-20 14:07:04.883  3581  3633 E AndroidRuntime: 	at com.hiddenramblings.tagmo.BrowserActivity$$ExternalSyntheticLambda25.run(Unknown Source:2)
12-20 14:07:04.883  3581  3633 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-20 14:07:04.883  3581  3633 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-20 14:07:04.883  3581  3633 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:920)
12-20 14:07:04.883  3581  3633 E UncaughtException: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
12-20 14:07:04.883  3581  3633 E UncaughtException: 	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:9316)
12-20 14:07:04.883  3581  3633 E UncaughtException: 	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1772)
12-20 14:07:04.883  3581  3633 E UncaughtException: 	at android.view.View.requestLayout(View.java:25697)
12-20 14:07:04.883  3581  3633 E UncaughtException: 	at android.view.View.requestLayout(View.java:25697)
12-20 14:07:04.883  3581  3633 E UncaughtException: 	at android.view.View.requestLayout(View.java:25697)
12-20 14:07:04.883  3581  3633 E UncaughtException: 	at android.view.View.requestLayout(View.java:25697)
12-20 14:07:04.883  3581  3633 E UncaughtException: 	at android.view.View.requestLayout(View.java:25697)
12-20 14:07:04.883  3581  3633 E UncaughtException: 	at android.view.View.requestLayout(View.java:25697)
12-20 14:07:04.883  3581  3633 E UncaughtException: 	at android.view.View.requestLayout(View.java:25697)
12-20 14:07:04.883  3581  3633 E UncaughtException: 	at android.view.View.setFlags(View.java:16377)
12-20 14:07:04.883  3581  3633 E UncaughtException: 	at android.view.View.setVisibility(View.java:11896)
12-20 14:07:04.883  3581  3633 E UncaughtException: 	at com.hiddenramblings.tagmo.BrowserActivity.lambda$locateKeyFiles$38$com-hiddenramblings-tagmo-BrowserActivity(BrowserActivity.java:1958)
12-20 14:07:04.883  3581  3633 E UncaughtException: 	at com.hiddenramblings.tagmo.BrowserActivity$$ExternalSyntheticLambda25.run(Unknown Source:2)
12-20 14:07:04.883  3581  3633 E UncaughtException: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-20 14:07:04.883  3581  3633 E UncaughtException: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-20 14:07:04.883  3581  3633 E UncaughtException: 	at java.lang.Thread.run(Thread.java:920)
12-20 14:07:04.883  3581  3633 W System.err: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
12-20 14:07:04.883  3581  3633 W System.err: 	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:9316)
12-20 14:07:04.883  3581  3633 W System.err: 	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1772)
12-20 14:07:04.883  3581  3633 W System.err: 	at android.view.View.requestLayout(View.java:25697)
12-20 14:07:04.883  3581  3633 W System.err: 	at android.view.View.requestLayout(View.java:25697)
12-20 14:07:04.883  3581  3633 W System.err: 	at android.view.View.requestLayout(View.java:25697)
12-20 14:07:04.883  3581  3633 W System.err: 	at android.view.View.requestLayout(View.java:25697)
12-20 14:07:04.883  3581  3633 W System.err: 	at android.view.View.requestLayout(View.java:25697)
12-20 14:07:04.883  3581  3633 W System.err: 	at android.view.View.requestLayout(View.java:25697)
12-20 14:07:04.883  3581  3633 W System.err: 	at android.view.View.requestLayout(View.java:25697)
12-20 14:07:04.883  3581  3633 W System.err: 	at android.view.View.setFlags(View.java:16377)
12-20 14:07:04.883  3581  3633 W System.err: 	at android.view.View.setVisibility(View.java:11896)
12-20 14:07:04.884  3581  3633 W System.err: 	at com.hiddenramblings.tagmo.BrowserActivity.lambda$locateKeyFiles$38$com-hiddenramblings-tagmo-BrowserActivity(BrowserActivity.java:1958)
12-20 14:07:04.884  3581  3633 W System.err: 	at com.hiddenramblings.tagmo.BrowserActivity$$ExternalSyntheticLambda25.run(Unknown Source:2)
12-20 14:07:04.884  3581  3633 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-20 14:07:04.884  3581  3633 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-20 14:07:04.884  3581  3633 W System.err: 	at java.lang.Thread.run(Thread.java:920)

**Comment by Tiberon** [comment]
All permissions are accepted for TagMo, and I have developer options enabled for other apps. Let me know if I've missed anything.

**Comment by Tiberon** [comment]
Nevermind, lol, I didn't follow instructions properly.

**Comment by Tiberon** [comment]
After following instructions for 1st launch, the issues persist. Reopening issue. Sorry for the churn.
