### ISSUE TITLE
8bit-link

### ISSUE THREAD

**Issue by LogcatGitHub** [HiddenRamblings/TagMo#414]
*Sent by [**acidfox086@gmail.com**](mailto:acidfox086@gmail.com)*

Description:
---

Zelda Breath of the wild amiiboo 8bit link backup ficha nfc

Device info:
---
<table>
<tr><td>App version</td><td>2.7.9</td></tr>
<tr><td>App version code</td><td>12</td></tr>
<tr><td>Android build version</td><td>V12.5.2.0.RCXEUXM</td></tr>
<tr><td>Android release version</td><td>11</td></tr>
<tr><td>Android SDK version</td><td>30</td></tr>
<tr><td>Android build ID</td><td>RKQ1.201004.002 test-keys</td></tr>
<tr><td>Device brand</td><td>xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>willow</td></tr>
<tr><td>Device model</td><td>Redmi Note 8T</td></tr>
<tr><td>Device product name</td><td>willow_eea</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

Logcat:
---
```TagMo - #da31532
Android R (11)

--------- beginning of system
02-23 20:36:10.665 27400 27400 I Timeline: Timeline: Activity_launch_request time:166208799
02-23 20:36:10.789 27400 27400 W Looper  : PerfMonitor looperActivity : package=com.hiddenramblings.tagmo/.BrowserActivity time=1ms latency=508ms running=0ms  procState=2 ClientTransaction{ callbacks=[android.app.servertransaction.TopResumedActivityChangeItem] } historyMsgCount=3 (msgIndex=2 wall=184ms seq=2 running=65ms runnable=25ms io=66ms late=7ms h=android.app.ActivityThread$H w=110) (msgIndex=3 wall=320ms seq=3 running=212ms runnable=14ms io=30ms late=188ms h=android.app.ActivityThread$H w=159)
02-23 20:36:11.148 27400 27400 W Looper  : PerfMonitor doFrame : time=334ms vsyncFrame=0 latency=45ms procState=2 historyMsgCount=26 (msgIndex=1 wall=320ms seq=3 running=212ms runnable=14ms io=30ms late=188ms h=android.app.ActivityThread$H w=159)
02-23 20:36:11.167 27400 27400 W Looper  : PerfMonitor doFrame : time=11ms vsyncFrame=0 latency=337ms procState=2 historyMsgCount=8 (msgIndex=1 wall=334ms seq=29 running=51ms runnable=4ms io=9ms late=45ms h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver)
02-23 20:36:47.380 27400 27400 W BpBinder: PerfMonitor binderTransact :  time=282ms interface=android.view.IWindowSession code=5
02-23 21:13:24.563 27400 27400 I Timeline: Timeline: Activity_launch_request time:166481991
--------- beginning of crash
02-23 21:13:30.306 27400 27400 E AndroidRuntime: FATAL EXCEPTION: main
02-23 21:13:30.306 27400 27400 E AndroidRuntime: Process: com.hiddenramblings.tagmo, PID: 27400
02-23 21:13:30.306 27400 27400 E AndroidRuntime: java.lang.RuntimeException: Unable to pause activity {com.hiddenramblings.tagmo/com.hiddenramblings.tagmo.NfcActivity}: java.lang.IllegalArgumentException: Receiver not registered: com.hiddenramblings.tagmo.NfcActivity$a@d412aa9
02-23 21:13:30.306 27400 27400 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4856)
02-23 21:13:30.306 27400 27400 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4807)
02-23 21:13:30.306 27400 27400 E AndroidRuntime: 	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4755)
02-23 21:13:30.306 27400 27400 E AndroidRuntime: 	at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:46)
02-23 21:13:30.306 27400 27400 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
02-23 21:13:30.306 27400 27400 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
02-23 21:13:30.306 27400 27400 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2135)
02-23 21:13:30.306 27400 27400 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-23 21:13:30.306 27400 27400 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:236)
02-23 21:13:30.306 27400 27400 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8037)
02-23 21:13:30.306 27400 27400 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-23 21:13:30.306 27400 27400 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
02-23 21:13:30.306 27400 27400 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
02-23 21:13:30.306 27400 27400 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Receiver not registered: com.hiddenramblings.tagmo.NfcActivity$a@d412aa9
02-23 21:13:30.306 27400 27400 E AndroidRuntime: 	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1439)
02-23 21:13:30.306 27400 27400 E AndroidRuntime: 	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1652)
02-23 21:13:30.306 27400 27400 E AndroidRuntime: 	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:726)
02-23 21:13:30.306 27400 27400 E AndroidRuntime: 	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:726)
02-23 21:13:30.306 27400 27400 E AndroidRuntime: 	at com.hiddenramblings.tagmo.NfcActivity.Q0(NfcActivity.java:3)
02-23 21:13:30.306 27400 27400 E AndroidRuntime: 	at com.hiddenramblings.tagmo.NfcActivity.onPause(NfcActivity.java:1)
02-23 21:13:30.306 27400 27400 E AndroidRuntime: 	at android.app.Activity.performPause(Activity.java:8358)
02-23 21:13:30.306 27400 27400 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1511)
02-23 21:13:30.306 27400 27400 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4846)
02-23 21:13:30.306 27400 27400 E AndroidRuntime: 	... 12 more
02-23 21:13:30.420 27400 27400 I Timeline: Timeline: Activity_launch_request time:166487849
02-23 21:20:01.168  7693  7693 W Looper  : PerfMonitor looperActivity : package=com.hiddenramblings.tagmo/.BrowserActivity time=0ms latency=460ms running=0ms  procState=2 ClientTransaction{ callbacks=[android.app.servertransaction.TopResumedActivityChangeItem] } historyMsgCount=2 (msgIndex=1 wall=179ms seq=2 running=77ms runnable=18ms io=64ms late=9ms h=android.app.ActivityThread$H w=110) (msgIndex=2 wall=313ms seq=3 running=230ms runnable=14ms io=21ms late=148ms h=android.app.ActivityThread$H w=159)
02-23 21:22:36.601 10613 10613 W Looper  : PerfMonitor looperActivity : package=com.hiddenramblings.tagmo/.BrowserActivity time=1ms latency=375ms running=0ms  procState=2 ClientTransaction{ callbacks=[android.app.servertransaction.TopResumedActivityChangeItem] } historyMsgCount=2 (msgIndex=1 wall=106ms seq=2 running=70ms runnable=10ms io=15ms late=14ms h=android.app.ActivityThread$H w=110) (msgIndex=2 wall=270ms seq=3 running=188ms runnable=12ms io=40ms late=107ms h=android.app.ActivityThread$H w=159)
02-23 22:58:01.605  9053  9053 W Looper  : PerfMonitor looperActivity : package=com.hiddenramblings.tagmo/.BrowserActivity time=0ms latency=339ms running=0ms  procState=2 ClientTransaction{ callbacks=[android.app.servertransaction.TopResumedActivityChangeItem] } historyMsgCount=2 (msgIndex=1 wall=116ms seq=2 running=61ms runnable=12ms io=33ms late=5ms h=android.app.ActivityThread$H w=110) (msgIndex=2 wall=227ms seq=3 running=176ms runnable=11ms io=17ms late=116ms h=android.app.ActivityThread$H w=159)
--------- beginning of main
02-23 23:00:28.936  9053  9053 W Choreographer: Frame time is 0.119853 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
02-23 23:00:40.907  9053  9053 W Choreographer: Frame time is 0.116742 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
02-23 23:00:47.038  9053  9053 I Timeline: Timeline: Activity_launch_request time:171827027
02-23 23:00:47.175  9053  9053 D DecorView[]: getWindowModeFromSystem  windowmode is 1
02-23 23:00:47.175  9053  9053 D DecorView: createDecorCaptionView windowingMode:1 mWindowMode 1 isFullscreen: true
02-23 23:00:47.225  9053  9053 D NFC     : Register Nfc adapter state changed receiver
02-23 23:00:47.225  9053  9053 I NFC     : registerAdapterStateChangedEvent()
02-23 23:00:47.248  9053  9053 D DecorView: createDecorCaptionView windowingMode:1 mWindowMode 1 isFullscreen: true
02-23 23:00:49.299  9053  9053 I Timeline: Timeline: Activity_launch_request time:171829288
02-23 23:00:49.700  9053  9053 W BpBinder: PerfMonitor binderTransact :  time=400ms interface=android.app.IActivityTaskManager code=1
02-23 23:00:49.711  9053  9053 W Looper  : PerfMonitor doFrame : time=0ms vsyncFrame=0 latency=401ms procState=2 historyMsgCount=2 (msgIndex=1 wall=401ms seq=1714 running=2ms runnable=2ms late=1ms h=androidx.appcompat.app.AlertController$g w=-1)
02-23 23:00:49.721  9053  9053 D AndroidRuntime: Shutting down VM
02-23 23:00:49.725  9053  9053 E AndroidRuntime: FATAL EXCEPTION: main
02-23 23:00:49.725  9053  9053 E AndroidRuntime: Process: com.hiddenramblings.tagmo, PID: 9053
02-23 23:00:49.725  9053  9053 E AndroidRuntime: java.lang.RuntimeException: Unable to pause activity {com.hiddenramblings.tagmo/com.hiddenramblings.tagmo.NfcActivity}: java.lang.IllegalArgumentException: Receiver not registered: com.hiddenramblings.tagmo.NfcActivity$a@2619725
02-23 23:00:49.725  9053  9053 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4856)
02-23 23:00:49.725  9053  9053 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4807)
02-23 23:00:49.725  9053  9053 E AndroidRuntime: 	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4755)
02-23 23:00:49.725  9053  9053 E AndroidRuntime: 	at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:46)
02-23 23:00:49.725  9053  9053 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
02-23 23:00:49.725  9053  9053 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
02-23 23:00:49.725  9053  9053 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2135)
02-23 23:00:49.725  9053  9053 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-23 23:00:49.725  9053  9053 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:236)
02-23 23:00:49.725  9053  9053 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8037)
02-23 23:00:49.725  9053  9053 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-23 23:00:49.725  9053  9053 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
02-23 23:00:49.725  9053  9053 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
02-23 23:00:49.725  9053  9053 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Receiver not registered: com.hiddenramblings.tagmo.NfcActivity$a@2619725
02-23 23:00:49.725  9053  9053 E AndroidRuntime: 	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1439)
02-23 23:00:49.725  9053  9053 E AndroidRuntime: 	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1652)
02-23 23:00:49.725  9053  9053 E AndroidRuntime: 	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:726)
02-23 23:00:49.725  9053  9053 E AndroidRuntime: 	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:726)
02-23 23:00:49.725  9053  9053 E AndroidRuntime: 	at com.hiddenramblings.tagmo.NfcActivity.Q0(NfcActivity.java:3)
02-23 23:00:49.725  9053  9053 E AndroidRuntime: 	at com.hiddenramblings.tagmo.NfcActivity.onPause(NfcActivity.java:1)
02-23 23:00:49.725  9053  9053 E AndroidRuntime: 	at android.app.Activity.performPause(Activity.java:8358)
02-23 23:00:49.725  9053  9053 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1511)
02-23 23:00:49.725  9053  9053 E AndroidRuntime: 	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4846)
02-23 23:00:49.725  9053  9053 E AndroidRuntime: 	... 12 more
02-23 23:00:49.735  9053  9053 E UncaughtException: java.lang.RuntimeException: Unable to pause activity {com.hiddenramblings.tagmo/com.hiddenramblings.tagmo.NfcActivity}: java.lang.IllegalArgumentException: Receiver not registered: com.hiddenramblings.tagmo.NfcActivity$a@2619725
02-23 23:00:49.735  9053  9053 E UncaughtException: 	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4856)
02-23 23:00:49.735  9053  9053 E UncaughtException: 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4807)
02-23 23:00:49.735  9053  9053 E UncaughtException: 	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4755)
02-23 23:00:49.735  9053  9053 E UncaughtException: 	at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:46)
02-23 23:00:49.735  9053  9053 E UncaughtException: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
02-23 23:00:49.735  9053  9053 E UncaughtException: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
02-23 23:00:49.735  9053  9053 E UncaughtException: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2135)
02-23 23:00:49.735  9053  9053 E UncaughtException: 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-23 23:00:49.735  9053  9053 E UncaughtException: 	at android.os.Looper.loop(Looper.java:236)
02-23 23:00:49.735  9053  9053 E UncaughtException: 	at android.app.ActivityThread.main(ActivityThread.java:8037)
02-23 23:00:49.735  9053  9053 E UncaughtException: 	at java.lang.reflect.Method.invoke(Native Method)
02-23 23:00:49.735  9053  9053 E UncaughtException: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
02-23 23:00:49.735  9053  9053 E UncaughtException: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
02-23 23:00:49.735  9053  9053 E UncaughtException: Caused by: java.lang.IllegalArgumentException: Receiver not registered: com.hiddenramblings.tagmo.NfcActivity$a@2619725
02-23 23:00:49.735  9053  9053 E UncaughtException: 	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1439)
02-23 23:00:49.735  9053  9053 E UncaughtException: 	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1652)
02-23 23:00:49.735  9053  9053 E UncaughtException: 	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:726)
02-23 23:00:49.735  9053  9053 E UncaughtException: 	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:726)
02-23 23:00:49.735  9053  9053 E UncaughtException: 	at com.hiddenramblings.tagmo.NfcActivity.Q0(NfcActivity.java:3)
02-23 23:00:49.735  9053  9053 E UncaughtException: 	at com.hiddenramblings.tagmo.NfcActivity.onPause(NfcActivity.java:1)
02-23 23:00:49.735  9053  9053 E UncaughtException: 	at android.app.Activity.performPause(Activity.java:8358)
02-23 23:00:49.735  9053  9053 E UncaughtException: 	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1511)
02-23 23:00:49.735  9053  9053 E UncaughtException: 	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4846)
02-23 23:00:49.735  9053  9053 E UncaughtException: 	... 12 more
02-23 23:00:49.737  9053  9053 W System.err: java.lang.RuntimeException: Unable to pause activity {com.hiddenramblings.tagmo/com.hiddenramblings.tagmo.NfcActivity}: java.lang.IllegalArgumentException: Receiver not registered: com.hiddenramblings.tagmo.NfcActivity$a@2619725
02-23 23:00:49.737  9053  9053 W System.err: 	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4856)
02-23 23:00:49.737  9053  9053 W System.err: 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4807)
02-23 23:00:49.737  9053  9053 W System.err: 	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4755)
02-23 23:00:49.737  9053  9053 W System.err: 	at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:46)
02-23 23:00:49.737  9053  9053 W System.err: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
02-23 23:00:49.737  9053  9053 W System.err: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
02-23 23:00:49.737  9053  9053 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2135)
02-23 23:00:49.737  9053  9053 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-23 23:00:49.737  9053  9053 W System.err: 	at android.os.Looper.loop(Looper.java:236)
02-23 23:00:49.737  9053  9053 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:8037)
02-23 23:00:49.737  9053  9053 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
02-23 23:00:49.737  9053  9053 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
02-23 23:00:49.737  9053  9053 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
02-23 23:00:49.737  9053  9053 W System.err: Caused by: java.lang.IllegalArgumentException: Receiver not registered: com.hiddenramblings.tagmo.NfcActivity$a@2619725
02-23 23:00:49.737  9053  9053 W System.err: 	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1439)
02-23 23:00:49.738  9053  9053 W System.err: 	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1652)
02-23 23:00:49.738  9053  9053 W System.err: 	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:726)
02-23 23:00:49.738  9053  9053 W System.err: 	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:726)
02-23 23:00:49.738  9053  9053 W System.err: 	at com.hiddenramblings.tagmo.NfcActivity.Q0(NfcActivity.java:3)
02-23 23:00:49.738  9053  9053 W System.err: 	at com.hiddenramblings.tagmo.NfcActivity.onPause(NfcActivity.java:1)
02-23 23:00:49.738  9053  9053 W System.err: 	at android.app.Activity.performPause(Activity.java:8358)
02-23 23:00:49.738  9053  9053 W System.err: 	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1511)
02-23 23:00:49.738  9053  9053 W System.err: 	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4846)
02-23 23:00:49.738  9053  9053 W System.err: 	... 12 more
```

**Comment by AbandonedCart** [comment]
Have you updated to the newest version?
