### ISSUE TITLE
Tagmo not correctly detecting Amiibo on Bluup Labs Flask

### ISSUE THREAD

**Issue by CoatsyJnr** [HiddenRamblings/TagMo#494]
### Issue Description

Tagmo incorrectly detecting amiibo on Bluup Labs Flask. Example: Super Mario Daisy is showing as Animal Crossing Daisy
![Screenshot_20220613-183011~2](https://user-images.githubusercontent.com/6701027/173559271-2dd720fa-9e8b-475d-ab02-2c65bc4c5528.png)
![Screenshot_20220613-183041](https://user-images.githubusercontent.com/6701027/173559287-88b3ff18-97ef-40a5-85fc-b491ceaa7331.png)

### Logcat Output

```shell
TagMo - #509ce39
Android S_V2 (12)

--------- beginning of main
06-14 20:42:38.692 32168 32168 E ramblings.tagm: Not starting debugger since process cannot load the jdwp agent.
06-14 20:42:38.713 32168 32168 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10411; state: ENABLED
06-14 20:42:38.744 32168 32168 D NetworkSecurityConfig: No Network Security Config specified, using platform default
06-14 20:42:38.744 32168 32168 D NetworkSecurityConfig: No Network Security Config specified, using platform default
06-14 20:42:38.753 32168 32186 D vulkan  : searching for layers in '/data/app/~~PeSa-V_EdZlTc_OZzYKYQQ==/com.hiddenramblings.tagmo-7Aj5mVL6Wjly7WE-EgiCKQ==/lib/arm64'
06-14 20:42:38.753 32168 32186 D vulkan  : searching for layers in '/data/app/~~PeSa-V_EdZlTc_OZzYKYQQ==/com.hiddenramblings.tagmo-7Aj5mVL6Wjly7WE-EgiCKQ==/base.apk!/lib/arm64-v8a'
06-14 20:42:38.760 32168 32186 D mali_cmarp_predictor: checking cmar_predictor for com.hiddenramblings.tagmo
06-14 20:42:38.795 32168 32168 D RenderScript HIDL Adaptation: IRenderScriptDevice::getService()
06-14 20:42:38.799 32168 32168 D RenderScript HIDL Adaptation: IRenderScriptDevice::getService() returned 0x0
06-14 20:42:38.799 32168 32168 D RenderScript HIDL Adaptation: Using Fallback Path.
06-14 20:42:38.828 32168 32168 D ramblings.tagm: Successfully queried cache dir: /data/user_de/0/com.hiddenramblings.tagmo/code_cache
06-14 20:42:38.828 32168 32168 D RenderScript: Setting cache dir: /data/user_de/0/com.hiddenramblings.tagmo/code_cache
06-14 20:42:38.831 32168 32168 I ContentCaptureHelper: Setting logging level to OFF
06-14 20:42:38.879 32168 32168 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-14 20:42:39.154 32168 32215 W Exception: java.lang.Exception: Data must start with 0x04.
06-14 20:42:39.154 32168 32215 W Exception: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.validateData(TagUtils.java:176)
06-14 20:42:39.154 32168 32215 W Exception: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.getValidatedData(TagUtils.java:260)
06-14 20:42:39.154 32168 32215 W Exception: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.getValidatedFile(TagUtils.java:267)
06-14 20:42:39.154 32168 32215 W Exception: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:298)
06-14 20:42:39.154 32168 32215 W Exception: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:295)
06-14 20:42:39.154 32168 32215 W Exception: 	at com.hiddenramblings.tagmo.BrowserActivity.lambda$loadAmiiboFiles$24(BrowserActivity.java:1329)
06-14 20:42:39.154 32168 32215 W Exception: 	at com.hiddenramblings.tagmo.BrowserActivity.$r8$lambda$FVwueBdhBCAV0uk4D1bcJ0ktJBc(Unknown Source:0)
06-14 20:42:39.154 32168 32215 W Exception: 	at com.hiddenramblings.tagmo.BrowserActivity$$ExternalSyntheticLambda40.run(Unknown Source:6)
06-14 20:42:39.154 32168 32215 W Exception: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-14 20:42:39.154 32168 32215 W Exception: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-14 20:42:39.154 32168 32215 W Exception: 	at java.lang.Thread.run(Thread.java:920)
06-14 20:42:39.160 32168 32215 W Exception: java.lang.Exception: Data must start with 0x04.
06-14 20:42:39.160 32168 32215 W Exception: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.validateData(TagUtils.java:176)
06-14 20:42:39.160 32168 32215 W Exception: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.getValidatedData(TagUtils.java:260)
06-14 20:42:39.160 32168 32215 W Exception: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.getValidatedFile(TagUtils.java:267)
06-14 20:42:39.160 32168 32215 W Exception: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:298)
06-14 20:42:39.160 32168 32215 W Exception: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:295)
06-14 20:42:39.160 32168 32215 W Exception: 	at com.hiddenramblings.tagmo.BrowserActivity.lambda$loadAmiiboFiles$24(BrowserActivity.java:1329)
06-14 20:42:39.160 32168 32215 W Exception: 	at com.hiddenramblings.tagmo.BrowserActivity.$r8$lambda$FVwueBdhBCAV0uk4D1bcJ0ktJBc(Unknown Source:0)
06-14 20:42:39.160 32168 32215 W Exception: 	at com.hiddenramblings.tagmo.BrowserActivity$$ExternalSyntheticLambda40.run(Unknown Source:6)
06-14 20:42:39.160 32168 32215 W Exception: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-14 20:42:39.160 32168 32215 W Exception: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-14 20:42:39.160 32168 32215 W Exception: 	at java.lang.Thread.run(Thread.java:920)
06-14 20:42:40.164 32168 32168 D CompatibilityChangeReporter: Compat change id reported: 171228096; UID 10411; state: ENABLED
06-14 20:42:40.192 32168 32168 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-14 20:42:40.192 32168 32168 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-14 20:42:40.192 32168 32168 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-14 20:42:40.192 32168 32168 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-14 20:42:40.360 32168 32215 W IOException: java.io.IOException: /storage/emulated/0/NFC/Amiibo Bins/key_retail.bin size: 160, Expected: 532
06-14 20:42:40.360 32168 32215 W IOException: 	at com.hiddenramblings.tagmo.nfctech.TagReader.getTagData(TagReader.java:35)
06-14 20:42:40.360 32168 32215 W IOException: 	at com.hiddenramblings.tagmo.nfctech.TagReader.readTagFile(TagReader.java:45)
06-14 20:42:40.360 32168 32215 W IOException: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.getValidatedFile(TagUtils.java:267)
06-14 20:42:40.360 32168 32215 W IOException: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:298)
06-14 20:42:40.360 32168 32215 W IOException: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:295)
06-14 20:42:40.360 32168 32215 W IOException: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:295)
06-14 20:42:40.360 32168 32215 W IOException: 	at com.hiddenramblings.tagmo.BrowserActivity.lambda$loadAmiiboFiles$24(BrowserActivity.java:1329)
06-14 20:42:40.360 32168 32215 W IOException: 	at com.hiddenramblings.tagmo.BrowserActivity.$r8$lambda$FVwueBdhBCAV0uk4D1bcJ0ktJBc(Unknown Source:0)
06-14 20:42:40.360 32168 32215 W IOException: 	at com.hiddenramblings.tagmo.BrowserActivity$$ExternalSyntheticLambda40.run(Unknown Source:6)
06-14 20:42:40.360 32168 32215 W IOException: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-14 20:42:40.360 32168 32215 W IOException: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-14 20:42:40.360 32168 32215 W IOException: 	at java.lang.Thread.run(Thread.java:920)
06-14 20:42:42.125 32168 32186 D OpenGLRenderer: endAllActiveAnimators on 0xb40000780ad71fa0 (MenuPopupWindow$MenuDropDownListView) with handle 0xb40000771acfd040
06-14 20:42:47.571 32168 32235 D CompatibilityChangeReporter: Compat change id reported: 160794467; UID 10411; state: ENABLED
06-14 20:42:52.473 32395 32395 E ramblings.tagm: Not starting debugger since process cannot load the jdwp agent.
06-14 20:42:52.490 32395 32395 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10411; state: ENABLED
06-14 20:42:52.598 32395 32395 D NetworkSecurityConfig: No Network Security Config specified, using platform default
06-14 20:42:52.600 32395 32395 D NetworkSecurityConfig: No Network Security Config specified, using platform default
06-14 20:42:56.217 32395 32456 D vulkan  : searching for layers in '/data/app/~~-jA47Yr0WRzoUMRa8-A8tQ==/com.hiddenramblings.tagmo-1BnqkMphlxc7nN_w1bzIag==/lib/arm64'
06-14 20:42:56.218 32395 32456 D vulkan  : searching for layers in '/data/app/~~-jA47Yr0WRzoUMRa8-A8tQ==/com.hiddenramblings.tagmo-1BnqkMphlxc7nN_w1bzIag==/base.apk!/lib/arm64-v8a'
06-14 20:42:56.229 32395 32456 D mali_cmarp_predictor: checking cmar_predictor for com.hiddenramblings.tagmo
06-14 20:42:56.279 32395 32395 D RenderScript HIDL Adaptation: IRenderScriptDevice::getService()
06-14 20:42:56.279 32395 32395 D RenderScript HIDL Adaptation: IRenderScriptDevice::getService() returned 0x0
06-14 20:42:56.279 32395 32395 D RenderScript HIDL Adaptation: Using Fallback Path.
06-14 20:42:56.289 32395 32395 D ramblings.tagm: Successfully queried cache dir: /data/user_de/0/com.hiddenramblings.tagmo/code_cache
06-14 20:42:56.289 32395 32395 D RenderScript: Setting cache dir: /data/user_de/0/com.hiddenramblings.tagmo/code_cache
06-14 20:42:56.298 32395 32395 I ContentCaptureHelper: Setting logging level to OFF
06-14 20:42:56.332 32395 32395 W View    : requestLayout() improperly called by android.widget.FrameLayout{283466 V.E...... ......ID 0,0-1440,2738 #2} during layout: running second layout pass
06-14 20:42:56.332 32395 32395 W View    : requestLayout() improperly called by androidx.recyclerview.widget.RecyclerView{21c8316 VFED.V... ......ID 0,0-1440,2734 #7f09005f app:id/amiibos_list} during layout: running second layout pass
06-14 20:42:56.400 32395 32395 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-14 20:42:56.596 32395 32482 W Exception: java.lang.Exception: Data must start with 0x04.
06-14 20:42:56.596 32395 32482 W Exception: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.validateData(TagUtils.java:176)
06-14 20:42:56.596 32395 32482 W Exception: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.getValidatedData(TagUtils.java:260)
06-14 20:42:56.596 32395 32482 W Exception: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.getValidatedFile(TagUtils.java:267)
06-14 20:42:56.596 32395 32482 W Exception: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:298)
06-14 20:42:56.596 32395 32482 W Exception: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:295)
06-14 20:42:56.596 32395 32482 W Exception: 	at com.hiddenramblings.tagmo.BrowserActivity.lambda$loadAmiiboFiles$30(BrowserActivity.java:1423)
06-14 20:42:56.596 32395 32482 W Exception: 	at com.hiddenramblings.tagmo.BrowserActivity.$r8$lambda$xY8n9YEkwX8BukamNio0wEVvcXs(Unknown Source:0)
06-14 20:42:56.596 32395 32482 W Exception: 	at com.hiddenramblings.tagmo.BrowserActivity$$ExternalSyntheticLambda45.run(Unknown Source:6)
06-14 20:42:56.596 32395 32482 W Exception: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-14 20:42:56.596 32395 32482 W Exception: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-14 20:42:56.596 32395 32482 W Exception: 	at java.lang.Thread.run(Thread.java:920)
06-14 20:42:56.600 32395 32482 W Exception: java.lang.Exception: Data must start with 0x04.
06-14 20:42:56.600 32395 32482 W Exception: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.validateData(TagUtils.java:176)
06-14 20:42:56.600 32395 32482 W Exception: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.getValidatedData(TagUtils.java:260)
06-14 20:42:56.600 32395 32482 W Exception: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.getValidatedFile(TagUtils.java:267)
06-14 20:42:56.600 32395 32482 W Exception: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:298)
06-14 20:42:56.600 32395 32482 W Exception: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:295)
06-14 20:42:56.600 32395 32482 W Exception: 	at com.hiddenramblings.tagmo.BrowserActivity.lambda$loadAmiiboFiles$30(BrowserActivity.java:1423)
06-14 20:42:56.600 32395 32482 W Exception: 	at com.hiddenramblings.tagmo.BrowserActivity.$r8$lambda$xY8n9YEkwX8BukamNio0wEVvcXs(Unknown Source:0)
06-14 20:42:56.600 32395 32482 W Exception: 	at com.hiddenramblings.tagmo.BrowserActivity$$ExternalSyntheticLambda45.run(Unknown Source:6)
06-14 20:42:56.600 32395 32482 W Exception: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-14 20:42:56.600 32395 32482 W Exception: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-14 20:42:56.600 32395 32482 W Exception: 	at java.lang.Thread.run(Thread.java:920)
06-14 20:42:56.629 32395 32488 W Exception: java.lang.Exception: Data must start with 0x04.
06-14 20:42:56.629 32395 32488 W Exception: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.validateData(TagUtils.java:176)
06-14 20:42:56.629 32395 32488 W Exception: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.getValidatedData(TagUtils.java:260)
06-14 20:42:56.629 32395 32488 W Exception: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.getValidatedFile(TagUtils.java:267)
06-14 20:42:56.629 32395 32488 W Exception: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:298)
06-14 20:42:56.629 32395 32488 W Exception: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:295)
06-14 20:42:56.629 32395 32488 W Exception: 	at com.hiddenramblings.tagmo.BrowserActivity.lambda$loadAmiiboFiles$30(BrowserActivity.java:1423)
06-14 20:42:56.629 32395 32488 W Exception: 	at com.hiddenramblings.tagmo.BrowserActivity.$r8$lambda$xY8n9YEkwX8BukamNio0wEVvcXs(Unknown Source:0)
06-14 20:42:56.629 32395 32488 W Exception: 	at com.hiddenramblings.tagmo.BrowserActivity$$ExternalSyntheticLambda45.run(Unknown Source:6)
06-14 20:42:56.629 32395 32488 W Exception: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-14 20:42:56.629 32395 32488 W Exception: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-14 20:42:56.629 32395 32488 W Exception: 	at java.lang.Thread.run(Thread.java:920)
06-14 20:42:56.632 32395 32488 W Exception: java.lang.Exception: Data must start with 0x04.
06-14 20:42:56.632 32395 32488 W Exception: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.validateData(TagUtils.java:176)
06-14 20:42:56.632 32395 32488 W Exception: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.getValidatedData(TagUtils.java:260)
06-14 20:42:56.632 32395 32488 W Exception: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.getValidatedFile(TagUtils.java:267)
06-14 20:42:56.632 32395 32488 W Exception: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:298)
06-14 20:42:56.632 32395 32488 W Exception: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:295)
06-14 20:42:56.632 32395 32488 W Exception: 	at com.hiddenramblings.tagmo.BrowserActivity.lambda$loadAmiiboFiles$30(BrowserActivity.java:1423)
06-14 20:42:56.632 32395 32488 W Exception: 	at com.hiddenramblings.tagmo.BrowserActivity.$r8$lambda$xY8n9YEkwX8BukamNio0wEVvcXs(Unknown Source:0)
06-14 20:42:56.632 32395 32488 W Exception: 	at com.hiddenramblings.tagmo.BrowserActivity$$ExternalSyntheticLambda45.run(Unknown Source:6)
06-14 20:42:56.632 32395 32488 W Exception: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-14 20:42:56.632 32395 32488 W Exception: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-14 20:42:56.632 32395 32488 W Exception: 	at java.lang.Thread.run(Thread.java:920)
06-14 20:42:56.668 32395 32494 W Exception: java.lang.Exception: Data must start with 0x04.
06-14 20:42:56.668 32395 32494 W Exception: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.validateData(TagUtils.java:176)
06-14 20:42:56.668 32395 32494 W Exception: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.getValidatedData(TagUtils.java:260)
06-14 20:42:56.668 32395 32494 W Exception: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.getValidatedFile(TagUtils.java:267)
06-14 20:42:56.668 32395 32494 W Exception: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:298)
06-14 20:42:56.668 32395 32494 W Exception: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:295)
06-14 20:42:56.668 32395 32494 W Exception: 	at com.hiddenramblings.tagmo.BrowserActivity.lambda$loadAmiiboFiles$30(BrowserActivity.java:1423)
06-14 20:42:56.668 32395 32494 W Exception: 	at com.hiddenramblings.tagmo.BrowserActivity.$r8$lambda$xY8n9YEkwX8BukamNio0wEVvcXs(Unknown Source:0)
06-14 20:42:56.668 32395 32494 W Exception: 	at com.hiddenramblings.tagmo.BrowserActivity$$ExternalSyntheticLambda45.run(Unknown Source:6)
06-14 20:42:56.668 32395 32494 W Exception: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-14 20:42:56.668 32395 32494 W Exception: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-14 20:42:56.668 32395 32494 W Exception: 	at java.lang.Thread.run(Thread.java:920)
06-14 20:42:56.670 32395 32494 W Exception: java.lang.Exception: Data must start with 0x04.
06-14 20:42:56.670 32395 32494 W Exception: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.validateData(TagUtils.java:176)
06-14 20:42:56.670 32395 32494 W Exception: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.getValidatedData(TagUtils.java:260)
06-14 20:42:56.670 32395 32494 W Exception: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.getValidatedFile(TagUtils.java:267)
06-14 20:42:56.670 32395 32494 W Exception: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:298)
06-14 20:42:56.670 32395 32494 W Exception: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:295)
06-14 20:42:56.670 32395 32494 W Exception: 	at com.hiddenramblings.tagmo.BrowserActivity.lambda$loadAmiiboFiles$30(BrowserActivity.java:1423)
06-14 20:42:56.670 32395 32494 W Exception: 	at com.hiddenramblings.tagmo.BrowserActivity.$r8$lambda$xY8n9YEkwX8BukamNio0wEVvcXs(Unknown Source:0)
06-14 20:42:56.670 32395 32494 W Exception: 	at com.hiddenramblings.tagmo.BrowserActivity$$ExternalSyntheticLambda45.run(Unknown Source:6)
06-14 20:42:56.670 32395 32494 W Exception: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-14 20:42:56.670 32395 32494 W Exception: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-14 20:42:56.670 32395 32494 W Exception: 	at java.lang.Thread.run(Thread.java:920)
06-14 20:42:57.090 32395 32482 W IOException: java.io.IOException: /storage/emulated/0/NFC/Amiibo Bins/key_retail.bin size: 160, Expected: 532
06-14 20:42:57.090 32395 32482 W IOException: 	at com.hiddenramblings.tagmo.nfctech.TagReader.getTagData(TagReader.java:35)
06-14 20:42:57.090 32395 32482 W IOException: 	at com.hiddenramblings.tagmo.nfctech.TagReader.readTagFile(TagReader.java:45)
06-14 20:42:57.090 32395 32482 W IOException: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.getValidatedFile(TagUtils.java:267)
06-14 20:42:57.090 32395 32482 W IOException: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:298)
06-14 20:42:57.090 32395 32482 W IOException: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:295)
06-14 20:42:57.090 32395 32482 W IOException: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:295)
06-14 20:42:57.090 32395 32482 W IOException: 	at com.hiddenramblings.tagmo.BrowserActivity.lambda$loadAmiiboFiles$30(BrowserActivity.java:1423)
06-14 20:42:57.090 32395 32482 W IOException: 	at com.hiddenramblings.tagmo.BrowserActivity.$r8$lambda$xY8n9YEkwX8BukamNio0wEVvcXs(Unknown Source:0)
06-14 20:42:57.090 32395 32482 W IOException: 	at com.hiddenramblings.tagmo.BrowserActivity$$ExternalSyntheticLambda45.run(Unknown Source:6)
06-14 20:42:57.090 32395 32482 W IOException: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-14 20:42:57.090 32395 32482 W IOException: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-14 20:42:57.090 32395 32482 W IOException: 	at java.lang.Thread.run(Thread.java:920)
06-14 20:42:57.156 32395 32488 W IOException: java.io.IOException: /storage/emulated/0/NFC/Amiibo Bins/key_retail.bin size: 160, Expected: 532
06-14 20:42:57.156 32395 32488 W IOException: 	at com.hiddenramblings.tagmo.nfctech.TagReader.getTagData(TagReader.java:35)
06-14 20:42:57.156 32395 32488 W IOException: 	at com.hiddenramblings.tagmo.nfctech.TagReader.readTagFile(TagReader.java:45)
06-14 20:42:57.156 32395 32488 W IOException: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.getValidatedFile(TagUtils.java:267)
06-14 20:42:57.156 32395 32488 W IOException: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:298)
06-14 20:42:57.156 32395 32488 W IOException: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:295)
06-14 20:42:57.156 32395 32488 W IOException: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:295)
06-14 20:42:57.156 32395 32488 W IOException: 	at com.hiddenramblings.tagmo.BrowserActivity.lambda$loadAmiiboFiles$30(BrowserActivity.java:1423)
06-14 20:42:57.156 32395 32488 W IOException: 	at com.hiddenramblings.tagmo.BrowserActivity.$r8$lambda$xY8n9YEkwX8BukamNio0wEVvcXs(Unknown Source:0)
06-14 20:42:57.156 32395 32488 W IOException: 	at com.hiddenramblings.tagmo.BrowserActivity$$ExternalSyntheticLambda45.run(Unknown Source:6)
06-14 20:42:57.156 32395 32488 W IOException: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-14 20:42:57.156 32395 32488 W IOException: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-14 20:42:57.156 32395 32488 W IOException: 	at java.lang.Thread.run(Thread.java:920)
06-14 20:42:57.204 32395 32494 W IOException: java.io.IOException: /storage/emulated/0/NFC/Amiibo Bins/key_retail.bin size: 160, Expected: 532
06-14 20:42:57.204 32395 32494 W IOException: 	at com.hiddenramblings.tagmo.nfctech.TagReader.getTagData(TagReader.java:35)
06-14 20:42:57.204 32395 32494 W IOException: 	at com.hiddenramblings.tagmo.nfctech.TagReader.readTagFile(TagReader.java:45)
06-14 20:42:57.204 32395 32494 W IOException: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.getValidatedFile(TagUtils.java:267)
06-14 20:42:57.204 32395 32494 W IOException: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:298)
06-14 20:42:57.204 32395 32494 W IOException: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:295)
06-14 20:42:57.204 32395 32494 W IOException: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:295)
06-14 20:42:57.204 32395 32494 W IOException: 	at com.hiddenramblings.tagmo.BrowserActivity.lambda$loadAmiiboFiles$30(BrowserActivity.java:1423)
06-14 20:42:57.204 32395 32494 W IOException: 	at com.hiddenramblings.tagmo.BrowserActivity.$r8$lambda$xY8n9YEkwX8BukamNio0wEVvcXs(Unknown Source:0)
06-14 20:42:57.204 32395 32494 W IOException: 	at com.hiddenramblings.tagmo.BrowserActivity$$ExternalSyntheticLambda45.run(Unknown Source:6)
06-14 20:42:57.204 32395 32494 W IOException: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
06-14 20:42:57.204 32395 32494 W IOException: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
06-14 20:42:57.204 32395 32494 W IOException: 	at java.lang.Thread.run(Thread.java:920)
06-14 20:42:57.380 32395 32395 D CompatibilityChangeReporter: Compat change id reported: 171228096; UID 10411; state: ENABLED
06-14 20:42:57.423 32395 32395 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-14 20:42:57.423 32395 32395 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-14 20:42:57.423 32395 32395 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-14 20:42:57.423 32395 32395 W TextView: onProvideContentCaptureStructure(): calling assumeLayout()
06-14 20:42:57.472 32395 32403 I ramblings.tagm: Background concurrent copying GC freed 734758(24MB) AllocSpace objects, 6(464KB) LOS objects, 75% free, 10MB/43MB, paused 91us,38us total 105.640ms
```

### Limitations and Requirements

- [X] I have read and understood the limitations and requirements

**Comment by AbandonedCart** [comment]
This is a known issue. The changes needed to fix it were recently added and this will be fixed when I return from vacation.
