### ISSUE TITLE
[Bug]: Crash on exit Flask

### ISSUE THREAD

**Issue by AbandonedCart** [HiddenRamblings/TagMo#498]
### Issue Description

See log for crash

### Logcat Output

```shell
TagMo - #a66961f
Android S (12)

--------- beginning of crash
06-15 12:34:33.439 22167 22167 E AndroidRuntime: FATAL EXCEPTION: main
06-15 12:34:33.439 22167 22167 E AndroidRuntime: Process: com.hiddenramblings.tagmo, PID: 22167
06-15 12:34:33.439 22167 22167 E AndroidRuntime: java.lang.RuntimeException: Unable to destroy activity {com.hiddenramblings.tagmo/com.hiddenramblings.tagmo.hardware.BluupFlaskActivity}: java.lang.IllegalArgumentException: Service not registered: com.hiddenramblings.tagmo.hardware.BluupFlaskActivity$1@d21c3ae
06-15 12:34:33.439 22167 22167 E AndroidRuntime: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5950)
06-15 12:34:33.439 22167 22167 E AndroidRuntime: 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5995)
06-15 12:34:33.439 22167 22167 E AndroidRuntime: 	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
06-15 12:34:33.439 22167 22167 E AndroidRuntime: 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
06-15 12:34:33.439 22167 22167 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
06-15 12:34:33.439 22167 22167 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
06-15 12:34:33.439 22167 22167 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
06-15 12:34:33.439 22167 22167 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-15 12:34:33.439 22167 22167 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
06-15 12:34:33.439 22167 22167 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
06-15 12:34:33.439 22167 22167 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8663)
06-15 12:34:33.439 22167 22167 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-15 12:34:33.439 22167 22167 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
06-15 12:34:33.439 22167 22167 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
06-15 12:34:33.439 22167 22167 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Service not registered: com.hiddenramblings.tagmo.hardware.BluupFlaskActivity$1@d21c3ae
06-15 12:34:33.439 22167 22167 E AndroidRuntime: 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:2038)
06-15 12:34:33.439 22167 22167 E AndroidRuntime: 	at android.app.ContextImpl.unbindService(ContextImpl.java:2099)
06-15 12:34:33.439 22167 22167 E AndroidRuntime: 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:863)
06-15 12:34:33.439 22167 22167 E AndroidRuntime: 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:863)
06-15 12:34:33.439 22167 22167 E AndroidRuntime: 	at com.hiddenramblings.tagmo.hardware.BluupFlaskActivity.stopFlaskService(BluupFlaskActivity.java:1032)
06-15 12:34:33.439 22167 22167 E AndroidRuntime: 	at com.hiddenramblings.tagmo.hardware.BluupFlaskActivity.disconnectFlask(BluupFlaskActivity.java:1028)
06-15 12:34:33.439 22167 22167 E AndroidRuntime: 	at com.hiddenramblings.tagmo.hardware.BluupFlaskActivity.onDestroy(BluupFlaskActivity.java:1108)
06-15 12:34:33.439 22167 22167 E AndroidRuntime: 	at android.app.Activity.performDestroy(Activity.java:8571)
06-15 12:34:33.439 22167 22167 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1364)
06-15 12:34:33.439 22167 22167 E AndroidRuntime: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5937)
06-15 12:34:33.439 22167 22167 E AndroidRuntime: 	... 13 more
06-15 12:34:33.440 22167 22167 E UncaughtException: java.lang.RuntimeException: Unable to destroy activity {com.hiddenramblings.tagmo/com.hiddenramblings.tagmo.hardware.BluupFlaskActivity}: java.lang.IllegalArgumentException: Service not registered: com.hiddenramblings.tagmo.hardware.BluupFlaskActivity$1@d21c3ae
06-15 12:34:33.440 22167 22167 E UncaughtException: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5950)
06-15 12:34:33.440 22167 22167 E UncaughtException: 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5995)
06-15 12:34:33.440 22167 22167 E UncaughtException: 	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
06-15 12:34:33.440 22167 22167 E UncaughtException: 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
06-15 12:34:33.440 22167 22167 E UncaughtException: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
06-15 12:34:33.440 22167 22167 E UncaughtException: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
06-15 12:34:33.440 22167 22167 E UncaughtException: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
06-15 12:34:33.440 22167 22167 E UncaughtException: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-15 12:34:33.440 22167 22167 E UncaughtException: 	at android.os.Looper.loopOnce(Looper.java:226)
06-15 12:34:33.440 22167 22167 E UncaughtException: 	at android.os.Looper.loop(Looper.java:313)
06-15 12:34:33.440 22167 22167 E UncaughtException: 	at android.app.ActivityThread.main(ActivityThread.java:8663)
06-15 12:34:33.440 22167 22167 E UncaughtException: 	at java.lang.reflect.Method.invoke(Native Method)
06-15 12:34:33.440 22167 22167 E UncaughtException: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
06-15 12:34:33.440 22167 22167 E UncaughtException: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
06-15 12:34:33.440 22167 22167 E UncaughtException: Caused by: java.lang.IllegalArgumentException: Service not registered: com.hiddenramblings.tagmo.hardware.BluupFlaskActivity$1@d21c3ae
06-15 12:34:33.440 22167 22167 E UncaughtException: 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:2038)
06-15 12:34:33.440 22167 22167 E UncaughtException: 	at android.app.ContextImpl.unbindService(ContextImpl.java:2099)
06-15 12:34:33.440 22167 22167 E UncaughtException: 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:863)
06-15 12:34:33.440 22167 22167 E UncaughtException: 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:863)
06-15 12:34:33.440 22167 22167 E UncaughtException: 	at com.hiddenramblings.tagmo.hardware.BluupFlaskActivity.stopFlaskService(BluupFlaskActivity.java:1032)
06-15 12:34:33.440 22167 22167 E UncaughtException: 	at com.hiddenramblings.tagmo.hardware.BluupFlaskActivity.disconnectFlask(BluupFlaskActivity.java:1028)
06-15 12:34:33.440 22167 22167 E UncaughtException: 	at com.hiddenramblings.tagmo.hardware.BluupFlaskActivity.onDestroy(BluupFlaskActivity.java:1108)
06-15 12:34:33.440 22167 22167 E UncaughtException: 	at android.app.Activity.performDestroy(Activity.java:8571)
06-15 12:34:33.440 22167 22167 E UncaughtException: 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1364)
06-15 12:34:33.440 22167 22167 E UncaughtException: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5937)
06-15 12:34:33.440 22167 22167 E UncaughtException: 	... 13 more
06-15 12:34:33.440 22167 22167 W System.err: java.lang.RuntimeException: Unable to destroy activity {com.hiddenramblings.tagmo/com.hiddenramblings.tagmo.hardware.BluupFlaskActivity}: java.lang.IllegalArgumentException: Service not registered: com.hiddenramblings.tagmo.hardware.BluupFlaskActivity$1@d21c3ae
06-15 12:34:33.440 22167 22167 W System.err: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5950)
06-15 12:34:33.440 22167 22167 W System.err: 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5995)
06-15 12:34:33.440 22167 22167 W System.err: 	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
06-15 12:34:33.440 22167 22167 W System.err: 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
06-15 12:34:33.440 22167 22167 W System.err: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
06-15 12:34:33.440 22167 22167 W System.err: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
06-15 12:34:33.440 22167 22167 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
06-15 12:34:33.440 22167 22167 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-15 12:34:33.440 22167 22167 W System.err: 	at android.os.Looper.loopOnce(Looper.java:226)
06-15 12:34:33.440 22167 22167 W System.err: 	at android.os.Looper.loop(Looper.java:313)
06-15 12:34:33.440 22167 22167 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:8663)
06-15 12:34:33.440 22167 22167 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
06-15 12:34:33.440 22167 22167 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
06-15 12:34:33.440 22167 22167 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
06-15 12:34:33.440 22167 22167 W System.err: Caused by: java.lang.IllegalArgumentException: Service not registered: com.hiddenramblings.tagmo.hardware.BluupFlaskActivity$1@d21c3ae
06-15 12:34:33.440 22167 22167 W System.err: 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:2038)
06-15 12:34:33.440 22167 22167 W System.err: 	at android.app.ContextImpl.unbindService(ContextImpl.java:2099)
06-15 12:34:33.440 22167 22167 W System.err: 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:863)
06-15 12:34:33.440 22167 22167 W System.err: 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:863)
06-15 12:34:33.440 22167 22167 W System.err: 	at com.hiddenramblings.tagmo.hardware.BluupFlaskActivity.stopFlaskService(BluupFlaskActivity.java:1032)
06-15 12:34:33.440 22167 22167 W System.err: 	at com.hiddenramblings.tagmo.hardware.BluupFlaskActivity.disconnectFlask(BluupFlaskActivity.java:1028)
06-15 12:34:33.440 22167 22167 W System.err: 	at com.hiddenramblings.tagmo.hardware.BluupFlaskActivity.onDestroy(BluupFlaskActivity.java:1108)
06-15 12:34:33.440 22167 22167 W System.err: 	at android.app.Activity.performDestroy(Activity.java:8571)
06-15 12:34:33.440 22167 22167 W System.err: 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1364)
06-15 12:34:33.440 22167 22167 W System.err: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5937)
06-15 12:34:33.440 22167 22167 W System.err: 	... 13 more
06-15 12:34:33.440 22167 22167 I ramblings.tagm: System.exit called, status: 1
```

### Limitations and Requirements

- [X] I have read and understood the limitations and requirements

**Comment by AbandonedCart** [comment]
Fixed
