### ISSUE TITLE
[Bug]: Crashing immediately upon opening

### ISSUE THREAD

**Issue by PlazmaDolphin** [HiddenRamblings/TagMo#528]
### Issue Description

I'm not sure if this is an issue on my part or with the app, but I tried opening it for the first time on a Samsung S4 mini. It flashed a few times, then crashed. I downloaded the sdk to an SD card with very limited space (64 MB), and installed it right after formatting the phone's memory.

### Logcat Output

```shell
2022-08-04 22:17:03.217 31217-31217/? E/UncaughtException: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.hiddenramblings.tagmo/com.hiddenramblings.tagmo.browser.BrowserActivity}: java.lang.StringIndexOutOfBoundsException: length=0; index=5
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471)
        at android.app.ActivityThread.access$900(ActivityThread.java:175)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:146)
        at android.app.ActivityThread.main(ActivityThread.java:5602)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.StringIndexOutOfBoundsException: length=0; index=5
        at java.lang.String.indexAndLength(String.java:584)
        at java.lang.String.substring(String.java:1449)
        at com.hiddenramblings.tagmo.eightbit.os.Storage.getRelativeDocument(Storage.java:265)
        at com.hiddenramblings.tagmo.browser.BrowserActivity.setFolderText(BrowserActivity.java:2410)
        at com.hiddenramblings.tagmo.browser.BrowserActivity.onBrowserSettingsChanged(BrowserActivity.java:1765)
        at com.hiddenramblings.tagmo.settings.BrowserSettings.notifyChanges(BrowserSettings.java:313)
        at com.hiddenramblings.tagmo.settings.SettingsFragment.onImageNetworkChange(SettingsFragment.java:231)
        at com.hiddenramblings.tagmo.settings.SettingsFragment.onCreate(SettingsFragment.java:88)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:3090)
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:257)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1890)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1808)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1751)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2976)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2886)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:351)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1177)
        at android.app.Activity.performStart(Activity.java:5461)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2386)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471) 
        at android.app.ActivityThread.access$900(ActivityThread.java:175) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:146) 
        at android.app.ActivityThread.main(ActivityThread.java:5602) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099) 
        at dalvik.system.NativeStart.main(Native Method) 
2022-08-04 22:17:03.217 31217-31217/? W/System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.hiddenramblings.tagmo/com.hiddenramblings.tagmo.browser.BrowserActivity}: java.lang.StringIndexOutOfBoundsException: length=0; index=5
2022-08-04 22:17:03.217 31217-31217/? W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
2022-08-04 22:17:03.217 31217-31217/? W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471)
2022-08-04 22:17:03.217 31217-31217/? W/System.err:     at android.app.ActivityThread.access$900(ActivityThread.java:175)
2022-08-04 22:17:03.217 31217-31217/? W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
2022-08-04 22:17:03.217 31217-31217/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
2022-08-04 22:17:03.217 31217-31217/? W/System.err:     at android.os.Looper.loop(Looper.java:146)
2022-08-04 22:17:03.217 31217-31217/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5602)
2022-08-04 22:17:03.217 31217-31217/? W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
2022-08-04 22:17:03.217 31217-31217/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
2022-08-04 22:17:03.217 31217-31217/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
2022-08-04 22:17:03.217 31217-31217/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
2022-08-04 22:17:03.217 31217-31217/? W/System.err:     at dalvik.system.NativeStart.main(Native Method)
2022-08-04 22:17:03.217 31217-31217/? W/System.err: Caused by: java.lang.StringIndexOutOfBoundsException: length=0; index=5
2022-08-04 22:17:03.217 31217-31217/? W/System.err:     at java.lang.String.indexAndLength(String.java:584)
2022-08-04 22:17:03.217 31217-31217/? W/System.err:     at java.lang.String.substring(String.java:1449)
2022-08-04 22:17:03.217 31217-31217/? W/System.err:     at com.hiddenramblings.tagmo.eightbit.os.Storage.getRelativeDocument(Storage.java:265)
2022-08-04 22:17:03.217 31217-31217/? W/System.err:     at com.hiddenramblings.tagmo.browser.BrowserActivity.setFolderText(BrowserActivity.java:2410)
2022-08-04 22:17:03.217 31217-31217/? W/System.err:     at com.hiddenramblings.tagmo.browser.BrowserActivity.onBrowserSettingsChanged(BrowserActivity.java:1765)
2022-08-04 22:17:03.217 31217-31217/? W/System.err:     at com.hiddenramblings.tagmo.settings.BrowserSettings.notifyChanges(BrowserSettings.java:313)
2022-08-04 22:17:03.217 31217-31217/? W/System.err:     at com.hiddenramblings.tagmo.settings.SettingsFragment.onImageNetworkChange(SettingsFragment.java:231)
2022-08-04 22:17:03.217 31217-31217/? W/System.err:     at com.hiddenramblings.tagmo.settings.SettingsFragment.onCreate(SettingsFragment.java:88)
2022-08-04 22:17:03.217 31217-31217/? W/System.err:     at androidx.fragment.app.Fragment.performCreate(Fragment.java:3090)
2022-08-04 22:17:03.217 31217-31217/? W/System.err:     at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
2022-08-04 22:17:03.217 31217-31217/? W/System.err:     at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:257)
2022-08-04 22:17:03.217 31217-31217/? W/System.err:     at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1890)
2022-08-04 22:17:03.217 31217-31217/? W/System.err:     at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1808)
2022-08-04 22:17:03.217 31217-31217/? W/System.err:     at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1751)
2022-08-04 22:17:03.217 31217-31217/? W/System.err:     at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2976)
2022-08-04 22:17:03.217 31217-31217/? W/System.err:     at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2886)
2022-08-04 22:17:03.227 31217-31217/? W/System.err:     at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
2022-08-04 22:17:03.227 31217-31217/? W/System.err:     at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:351)
2022-08-04 22:17:03.227 31217-31217/? W/System.err:     at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
2022-08-04 22:17:03.227 31217-31217/? W/System.err:     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1177)
2022-08-04 22:17:03.227 31217-31217/? W/System.err:     at android.app.Activity.performStart(Activity.java:5461)
2022-08-04 22:17:03.227 31217-31217/? W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2386)
2022-08-04 22:17:03.227 31217-31217/? W/System.err: 	... 11 more
```

### Limitations and Requirements

- [X] I have read and understood the limitations and requirements

**Comment by AbandonedCart** [comment]
How to determine the cause of a crash is almost always from the log, which was (ironically) marked not applicable (or N/A).

**Comment by AbandonedCart** [comment]
Crashes that cause the application to close, also called exceptions, are passed through a section of the log labeled 'AndroidRuntimeException'. They will list the type of exception, such as a 'NullPointerException' (variable being read is null). More importantly, they will list the specific file and even the line number that caused the error. As you might have guessed, this means we not only know what is wrong, but exactly where to find it. Instead of a tedious process attempting to recreate the exact scenario to reproduce the issue and then trying to eliminate unlikely causes until possible fixes can be attempted, the entire task is reduced to mere minutes. This is why logs are marked required.

**Comment by PlazmaDolphin** [comment]
Oooh I didn't know what logcat meant, so sorry. Where can I find the error file, I'm not familiar with Android file system.

**Comment by AbandonedCart** [comment]
Since it's an instant crash, the feature to retrieve the log probably won't be available. Was it downloaded from Google Play or GitHub?

**Comment by PlazmaDolphin** [comment]
I put the sdk from github on a microSD using my computer, then put the microSD in the phone and installed it. I figured out how to logcat in the meantime, and got about 2000 lines of debug from the 5 seconds it ran, which I put into this pastebin: https://pastebin.com/ZtTZape5

**Comment by AbandonedCart** [comment]
Thanks. In the future, the logcat should be available in the clipboard even if the app crashes instantly, which is what happens when using the menu option now. I thought that had already been added, but apparently it got lost somewhere in other changes.
