### ISSUE TITLE
[Bug]: App seems slower in newest build

### ISSUE THREAD

**Issue by RonanM1** [HiddenRamblings/TagMo#534]
### Issue Description

It's just very laggy when I updated the app and the old version runs more smoothly than this ;/

### Logcat Output

```shell
TagMo - #870a8e2
Android R (11)
Installed by release

--------- beginning of main
08-09 15:28:56.356  6111  6111 E ramblings.tagm: Not starting debugger since process cannot load the jdwp agent.
08-09 15:28:56.428  6111  6111 D NetworkSecurityConfig: No Network Security Config specified, using platform default
08-09 15:28:56.428  6111  6111 D NetworkSecurityConfig: No Network Security Config specified, using platform default
08-09 15:28:56.535  6111  6142 D libMEOW : meow reload base cfg path: na
08-09 15:28:56.535  6111  6142 D libMEOW : meow reload overlay cfg path: na
08-09 15:28:56.536  6111  6142 D libMEOW : applied 1 plugins for [com.hiddenramblings.tagmo]:
08-09 15:28:56.536  6111  6142 D libMEOW :   plugin 1: [libMEOW_gift.so]:
08-09 15:28:56.733  6111  6111 D RenderScript HIDL Adaptation: IRenderScriptDevice::getService()
08-09 15:28:56.780  6111  6111 D RenderScript HIDL Adaptation: IRenderScriptDevice::getService() returned 0xb400007df0489300
08-09 15:28:56.780  6111  6111 D RenderScript HIDL Adaptation: HIDL successfully loaded.
08-09 15:28:56.781  6111  6144 E RenderScript: Failed loading RS driver: dlopen failed: library "libRSDriver_mtk.so" not found
08-09 15:28:56.781  6111  6144 E RenderScript: Failed to load runtime libRSDriver_mtk.so, loading default
08-09 15:28:56.800  6111  6111 D ramblings.tagm: Successfully queried cache dir: /data/user_de/0/com.hiddenramblings.tagmo/code_cache
08-09 15:28:56.800  6111  6111 D RenderScript: Setting cache dir: /data/user_de/0/com.hiddenramblings.tagmo/code_cache
08-09 15:28:56.839  6111  6155 W IOException: java.io.IOException: /storage/emulated/0/Download/Tag bin/key_retail.bin size: 160, Expected: 532
08-09 15:28:56.839  6111  6155 W IOException: 	at com.hiddenramblings.tagmo.nfctech.TagReader.getTagData(TagReader.java:35)
08-09 15:28:56.839  6111  6155 W IOException: 	at com.hiddenramblings.tagmo.nfctech.TagReader.readTagFile(TagReader.java:45)
08-09 15:28:56.839  6111  6155 W IOException: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.getValidatedFile(TagUtils.java:327)
08-09 15:28:56.839  6111  6155 W IOException: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:298)
08-09 15:28:56.839  6111  6155 W IOException: 	at com.hiddenramblings.tagmo.browser.BrowserActivity.lambda$loadAmiiboFiles$37(BrowserActivity.java:1640)
08-09 15:28:56.839  6111  6155 W IOException: 	at com.hiddenramblings.tagmo.browser.BrowserActivity.$r8$lambda$RD-AcKkKseTe4X6J0sl9l39k6rU(Unknown Source:0)
08-09 15:28:56.839  6111  6155 W IOException: 	at com.hiddenramblings.tagmo.browser.BrowserActivity$$ExternalSyntheticLambda72.run(Unknown Source:6)
08-09 15:28:56.839  6111  6155 W IOException: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-09 15:28:56.839  6111  6155 W IOException: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-09 15:28:56.839  6111  6155 W IOException: 	at java.lang.Thread.run(Thread.java:923)
08-09 15:28:56.840  6111  6167 W IOException: java.io.IOException: /storage/emulated/0/Download/Tag bin/key_retail.bin size: 160, Expected: 532
08-09 15:28:56.840  6111  6167 W IOException: 	at com.hiddenramblings.tagmo.nfctech.TagReader.getTagData(TagReader.java:35)
08-09 15:28:56.840  6111  6167 W IOException: 	at com.hiddenramblings.tagmo.nfctech.TagReader.readTagFile(TagReader.java:45)
08-09 15:28:56.840  6111  6167 W IOException: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.getValidatedFile(TagUtils.java:327)
08-09 15:28:56.840  6111  6167 W IOException: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:298)
08-09 15:28:56.840  6111  6167 W IOException: 	at com.hiddenramblings.tagmo.browser.BrowserActivity.lambda$loadAmiiboFiles$37(BrowserActivity.java:1640)
08-09 15:28:56.840  6111  6167 W IOException: 	at com.hiddenramblings.tagmo.browser.BrowserActivity.$r8$lambda$RD-AcKkKseTe4X6J0sl9l39k6rU(Unknown Source:0)
08-09 15:28:56.840  6111  6167 W IOException: 	at com.hiddenramblings.tagmo.browser.BrowserActivity$$ExternalSyntheticLambda72.run(Unknown Source:6)
08-09 15:28:56.840  6111  6167 W IOException: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-09 15:28:56.840  6111  6167 W IOException: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-09 15:28:56.840  6111  6167 W IOException: 	at java.lang.Thread.run(Thread.java:923)
08-09 15:28:56.860  6111  6155 W IOException: java.io.IOException: /storage/emulated/0/Download/Tag bin/Amiibo Bins 540-572/key_retail.bin size: 160, Expected: 532
08-09 15:28:56.860  6111  6155 W IOException: 	at com.hiddenramblings.tagmo.nfctech.TagReader.getTagData(TagReader.java:35)
08-09 15:28:56.860  6111  6155 W IOException: 	at com.hiddenramblings.tagmo.nfctech.TagReader.readTagFile(TagReader.java:45)
08-09 15:28:56.860  6111  6155 W IOException: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.getValidatedFile(TagUtils.java:327)
08-09 15:28:56.860  6111  6155 W IOException: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:298)
08-09 15:28:56.860  6111  6155 W IOException: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:295)
08-09 15:28:56.860  6111  6155 W IOException: 	at com.hiddenramblings.tagmo.browser.BrowserActivity.lambda$loadAmiiboFiles$37(BrowserActivity.java:1640)
08-09 15:28:56.860  6111  6155 W IOException: 	at com.hiddenramblings.tagmo.browser.BrowserActivity.$r8$lambda$RD-AcKkKseTe4X6J0sl9l39k6rU(Unknown Source:0)
08-09 15:28:56.860  6111  6155 W IOException: 	at com.hiddenramblings.tagmo.browser.BrowserActivity$$ExternalSyntheticLambda72.run(Unknown Source:6)
08-09 15:28:56.860  6111  6155 W IOException: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-09 15:28:56.860  6111  6155 W IOException: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-09 15:28:56.860  6111  6155 W IOException: 	at java.lang.Thread.run(Thread.java:923)
08-09 15:28:56.865  6111  6167 W IOException: java.io.IOException: /storage/emulated/0/Download/Tag bin/Amiibo Bins 540-572/key_retail.bin size: 160, Expected: 532
08-09 15:28:56.865  6111  6167 W IOException: 	at com.hiddenramblings.tagmo.nfctech.TagReader.getTagData(TagReader.java:35)
08-09 15:28:56.865  6111  6167 W IOException: 	at com.hiddenramblings.tagmo.nfctech.TagReader.readTagFile(TagReader.java:45)
08-09 15:28:56.865  6111  6167 W IOException: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.getValidatedFile(TagUtils.java:327)
08-09 15:28:56.865  6111  6167 W IOException: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:298)
08-09 15:28:56.865  6111  6167 W IOException: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:295)
08-09 15:28:56.865  6111  6167 W IOException: 	at com.hiddenramblings.tagmo.browser.BrowserActivity.lambda$loadAmiiboFiles$37(BrowserActivity.java:1640)
08-09 15:28:56.865  6111  6167 W IOException: 	at com.hiddenramblings.tagmo.browser.BrowserActivity.$r8$lambda$RD-AcKkKseTe4X6J0sl9l39k6rU(Unknown Source:0)
08-09 15:28:56.865  6111  6167 W IOException: 	at com.hiddenramblings.tagmo.browser.BrowserActivity$$ExternalSyntheticLambda72.run(Unknown Source:6)
08-09 15:28:56.865  6111  6167 W IOException: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-09 15:28:56.865  6111  6167 W IOException: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-09 15:28:56.865  6111  6167 W IOException: 	at java.lang.Thread.run(Thread.java:923)
08-09 15:28:56.890  6111  6111 D libMEOW : applied 1 plugins for [com.hiddenramblings.tagmo]:
08-09 15:28:56.890  6111  6111 D libMEOW :   plugin 1: [libMEOW_gift.so]:
08-09 15:28:56.891  6111  6111 I InputTransport: Create ARC handle: 0xb400007de5cd6b20
08-09 15:28:56.931  6111  6140 D libMEOW : applied 1 plugins for [com.hiddenramblings.tagmo]:
08-09 15:28:56.931  6111  6140 D libMEOW :   plugin 1: [libMEOW_gift.so]:
08-09 15:28:56.947  6111  6140 I GED     : [GT]_get_procNameprocess pid(6111)
08-09 15:28:56.947  6111  6140 I GED     : [GT]_getprocess name(com.hiddenramblings.tagmo)
08-09 15:28:56.947  6111  6140 I ramblings.tagm: [GT] ret(1) gt_status(00000000) aniso_debug_level(0) gt_aniso_max_level(16) ani so mask(00000001) tri mask(00000002)
08-09 15:28:56.947  6111  6140 I libMEOW_gift: ctx:0xb400007d9a7cfee8, ARC not Enabled.
08-09 15:28:56.980  6111  6201 W IOException: java.io.IOException: /storage/emulated/0/Download/Tag bin/key_retail.bin size: 160, Expected: 532
08-09 15:28:56.980  6111  6201 W IOException: 	at com.hiddenramblings.tagmo.nfctech.TagReader.getTagData(TagReader.java:35)
08-09 15:28:56.980  6111  6201 W IOException: 	at com.hiddenramblings.tagmo.nfctech.TagReader.readTagFile(TagReader.java:45)
08-09 15:28:56.980  6111  6201 W IOException: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.getValidatedFile(TagUtils.java:327)
08-09 15:28:56.980  6111  6201 W IOException: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:298)
08-09 15:28:56.980  6111  6201 W IOException: 	at com.hiddenramblings.tagmo.browser.BrowserActivity.lambda$loadAmiiboFiles$37(BrowserActivity.java:1640)
08-09 15:28:56.980  6111  6201 W IOException: 	at com.hiddenramblings.tagmo.browser.BrowserActivity.$r8$lambda$RD-AcKkKseTe4X6J0sl9l39k6rU(Unknown Source:0)
08-09 15:28:56.980  6111  6201 W IOException: 	at com.hiddenramblings.tagmo.browser.BrowserActivity$$ExternalSyntheticLambda72.run(Unknown Source:6)
08-09 15:28:56.980  6111  6201 W IOException: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-09 15:28:56.980  6111  6201 W IOException: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-09 15:28:56.980  6111  6201 W IOException: 	at java.lang.Thread.run(Thread.java:923)
08-09 15:28:56.989  6111  6201 W IOException: java.io.IOException: /storage/emulated/0/Download/Tag bin/Amiibo Bins 540-572/key_retail.bin size: 160, Expected: 532
08-09 15:28:56.989  6111  6201 W IOException: 	at com.hiddenramblings.tagmo.nfctech.TagReader.getTagData(TagReader.java:35)
08-09 15:28:56.989  6111  6201 W IOException: 	at com.hiddenramblings.tagmo.nfctech.TagReader.readTagFile(TagReader.java:45)
08-09 15:28:56.989  6111  6201 W IOException: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.getValidatedFile(TagUtils.java:327)
08-09 15:28:56.989  6111  6201 W IOException: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:298)
08-09 15:28:56.989  6111  6201 W IOException: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:295)
08-09 15:28:56.989  6111  6201 W IOException: 	at com.hiddenramblings.tagmo.browser.BrowserActivity.lambda$loadAmiiboFiles$37(BrowserActivity.java:1640)
08-09 15:28:56.989  6111  6201 W IOException: 	at com.hiddenramblings.tagmo.browser.BrowserActivity.$r8$lambda$RD-AcKkKseTe4X6J0sl9l39k6rU(Unknown Source:0)
08-09 15:28:56.989  6111  6201 W IOException: 	at com.hiddenramblings.tagmo.browser.BrowserActivity$$ExternalSyntheticLambda72.run(Unknown Source:6)
08-09 15:28:56.989  6111  6201 W IOException: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-09 15:28:56.989  6111  6201 W IOException: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-09 15:28:56.989  6111  6201 W IOException: 	at java.lang.Thread.run(Thread.java:923)
08-09 15:28:57.036  6111  6167 W Exception: java.lang.Exception: Data must start with 0x04.
08-09 15:28:57.036  6111  6167 W Exception: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.validateData(TagUtils.java:231)
08-09 15:28:57.036  6111  6167 W Exception: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.getValidatedData(TagUtils.java:320)
08-09 15:28:57.036  6111  6167 W Exception: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.getValidatedFile(TagUtils.java:327)
08-09 15:28:57.036  6111  6167 W Exception: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:298)
08-09 15:28:57.036  6111  6167 W Exception: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:295)
08-09 15:28:57.036  6111  6167 W Exception: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:295)
08-09 15:28:57.036  6111  6167 W Exception: 	at com.hiddenramblings.tagmo.browser.BrowserActivity.lambda$loadAmiiboFiles$37(BrowserActivity.java:1640)
08-09 15:28:57.036  6111  6167 W Exception: 	at com.hiddenramblings.tagmo.browser.BrowserActivity.$r8$lambda$RD-AcKkKseTe4X6J0sl9l39k6rU(Unknown Source:0)
08-09 15:28:57.036  6111  6167 W Exception: 	at com.hiddenramblings.tagmo.browser.BrowserActivity$$ExternalSyntheticLambda72.run(Unknown Source:6)
08-09 15:28:57.036  6111  6167 W Exception: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-09 15:28:57.036  6111  6167 W Exception: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-09 15:28:57.036  6111  6167 W Exception: 	at java.lang.Thread.run(Thread.java:923)
08-09 15:28:57.074  6111  6155 W Exception: java.lang.Exception: Data must start with 0x04.
08-09 15:28:57.074  6111  6155 W Exception: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.validateData(TagUtils.java:231)
08-09 15:28:57.074  6111  6155 W Exception: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.getValidatedData(TagUtils.java:320)
08-09 15:28:57.074  6111  6155 W Exception: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.getValidatedFile(TagUtils.java:327)
08-09 15:28:57.074  6111  6155 W Exception: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:298)
08-09 15:28:57.074  6111  6155 W Exception: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:295)
08-09 15:28:57.074  6111  6155 W Exception: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:295)
08-09 15:28:57.074  6111  6155 W Exception: 	at com.hiddenramblings.tagmo.browser.BrowserActivity.lambda$loadAmiiboFiles$37(BrowserActivity.java:1640)
08-09 15:28:57.074  6111  6155 W Exception: 	at com.hiddenramblings.tagmo.browser.BrowserActivity.$r8$lambda$RD-AcKkKseTe4X6J0sl9l39k6rU(Unknown Source:0)
08-09 15:28:57.074  6111  6155 W Exception: 	at com.hiddenramblings.tagmo.browser.BrowserActivity$$ExternalSyntheticLambda72.run(Unknown Source:6)
08-09 15:28:57.074  6111  6155 W Exception: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-09 15:28:57.074  6111  6155 W Exception: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-09 15:28:57.074  6111  6155 W Exception: 	at java.lang.Thread.run(Thread.java:923)
08-09 15:28:57.096  6111  6111 W View    : requestLayout() improperly called by android.widget.FrameLayout{e3ea7d4 V.E..V... ......ID 0,0-1080,2025 #2} during layout: running second layout pass
08-09 15:28:57.096  6111  6111 W View    : requestLayout() improperly called by myinnos.indexfastscrollrecycler.IndexFastScrollRecyclerView{b40b121 VFED.V... ......ID 0,1712-1080,2022 #7f09010f app:id/foomiibo_list} during layout: running second layout pass
08-09 15:28:57.096  6111  6111 W View    : requestLayout() improperly called by myinnos.indexfastscrollrecycler.IndexFastScrollRecyclerView{649150f VFED.V... ......ID 0,0-1080,1642 #7f09005f app:id/amiibos_list} during layout: running second layout pass
08-09 15:28:57.110  6111  6140 E ion     : ioctl c0044901 failed with code -1: Invalid argument
08-09 15:28:57.157  6111  6201 W Exception: java.lang.Exception: Data must start with 0x04.
08-09 15:28:57.157  6111  6201 W Exception: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.validateData(TagUtils.java:231)
08-09 15:28:57.157  6111  6201 W Exception: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.getValidatedData(TagUtils.java:320)
08-09 15:28:57.157  6111  6201 W Exception: 	at com.hiddenramblings.tagmo.nfctech.TagUtils.getValidatedFile(TagUtils.java:327)
08-09 15:28:57.157  6111  6201 W Exception: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:298)
08-09 15:28:57.157  6111  6201 W Exception: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:295)
08-09 15:28:57.157  6111  6201 W Exception: 	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiibos(AmiiboManager.java:295)
08-09 15:28:57.157  6111  6201 W Exception: 	at com.hiddenramblings.tagmo.browser.BrowserActivity.lambda$loadAmiiboFiles$37(BrowserActivity.java:1640)
08-09 15:28:57.157  6111  6201 W Exception: 	at com.hiddenramblings.tagmo.browser.BrowserActivity.$r8$lambda$RD-AcKkKseTe4X6J0sl9l39k6rU(Unknown Source:0)
08-09 15:28:57.157  6111  6201 W Exception: 	at com.hiddenramblings.tagmo.browser.BrowserActivity$$ExternalSyntheticLambda72.run(Unknown Source:6)
08-09 15:28:57.157  6111  6201 W Exception: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-09 15:28:57.157  6111  6201 W Exception: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-09 15:28:57.157  6111  6201 W Exception: 	at java.lang.Thread.run(Thread.java:923)
08-09 15:28:57.342  6111  6111 I Choreographer: Skipped 52 frames!  The application may be doing too much work on its main thread.
08-09 15:28:57.563  6111  6111 I TetheringManager: registerTetheringEventCallback:com.hiddenramblings.tagmo
08-09 15:28:59.089  6111  6235 W Filter  : An exception occured during performFiltering()!
08-09 15:28:59.089  6111  6235 W Filter  : java.util.ConcurrentModificationException
08-09 15:28:59.089  6111  6235 W Filter  : 	at java.util.ArrayList$Itr.next(ArrayList.java:860)
08-09 15:28:59.089  6111  6235 W Filter  : 	at com.hiddenramblings.tagmo.browser.adapter.BrowserAdapter$AmiiboFilter.performFiltering(BrowserAdapter.java:274)
08-09 15:28:59.089  6111  6235 W Filter  : 	at android.widget.Filter$RequestHandler.handleMessage(Filter.java:236)
08-09 15:28:59.089  6111  6235 W Filter  : 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-09 15:28:59.089  6111  6235 W Filter  : 	at android.os.Looper.loop(Looper.java:250)
08-09 15:28:59.089  6111  6235 W Filter  : 	at android.os.HandlerThread.run(HandlerThread.java:67)
08-09 15:29:00.060  6111  6111 I Choreographer: Skipped 47 frames!  The application may be doing too much work on its main thread.
08-09 15:29:00.321  6111  6111 I Choreographer: Skipped 30 frames!  The application may be doing too much work on its main thread.
08-09 15:29:01.691  6111  6127 I ramblings.tagm: Background concurrent copying GC freed 593304(17MB) AllocSpace objects, 77(7508KB) LOS objects, 49% free, 8686KB/16MB, paused 57us total 124.392ms
08-09 15:29:02.755  6111  6111 I InputTransport: Create ARC handle: 0xb400007d6e123b80
08-09 15:29:02.769  6111  6111 I Choreographer: Skipped 48 frames!  The application may be doing too much work on its main thread.
08-09 15:29:03.411  6111  6140 I OpenGLRenderer: Davey! duration=1045ms; Flags=1, IntendedVsync=54930109087172, Vsync=54930509087156, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=54930512623598, AnimationStart=54930512624598, PerformTraversalsStart=54930513204598, DrawStart=54931140202815, SyncQueued=54931141248661, SyncStart=54931141545507, IssueDrawCommandsStart=54931141612046, SwapBuffers=54931152986508, FrameCompleted=54931154459432, DequeueBufferDuration=149539, QueueBufferDuration=345616, GpuCompleted=0, 
08-09 15:29:03.416  6111  6111 I Choreographer: Skipped 76 frames!  The application may be doing too much work on its main thread.
08-09 15:29:03.614  6111  6140 I OpenGLRenderer: Davey! duration=831ms; Flags=0, IntendedVsync=54930525645097, Vsync=54931158978405, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=54931159740971, AnimationStart=54931159743048, PerformTraversalsStart=54931160675432, DrawStart=54931161604586, SyncQueued=54931167686202, SyncStart=54931168040895, IssueDrawCommandsStart=54931168363048, SwapBuffers=54931355157221, FrameCompleted=54931357414529, DequeueBufferDuration=292384, QueueBufferDuration=528000, GpuCompleted=0, 
08-09 15:29:05.025  6255  6255 W logcat  : type=1400 audit(0.0:26345): avc: denied { search } for name="mm" dev="sysfs" ino=7076 scontext=u:r:untrusted_app:s0:c130,c257,c512,c768 tcontext=u:object_r:sysfs_mm:s0 tclass=dir permissive=0 app=com.hiddenramblings.tagmo
```

### Limitations and Requirements

- [X] I have read and understood the limitations and requirements

**Comment by AbandonedCart** [comment]
Thanks for the feedback. Using "All Files" permission and settings your folder to the one where only your bin files are stored will improve the speed.
