### ISSUE TITLE
[Bug]: Decryption error

### ISSUE THREAD

**Issue by OreoJournal** [HiddenRamblings/TagMo#577]
### Issue Description

When I scan a NTAG215 card to write it to an amiibo it says "Failed to decrypt tag data" When I go to check the data validation it says "lock signature mismatch." The only way I can change this is to scan a card I had used a while ago to make an amiibo, then click update, and scan a new card. It'll then put that already made amiibo onto that new card and everything seems to be fine afterwards but now I'm stuck with multiple cards for one amiibo connected to my account.

### Logcat Output

```shell
TagMo - #420566f4
Android S (12)
10.07 GB RAM
Installed by publish

java.lang.SecurityException: Permission Denial: opening provider com.android.externalstorage.ExternalStorageProvider from ProcessRecord{f140e83 16704:com.hiddenramblings.tagmo.eightbit/u0a860} (pid=16704, uid=10860) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2438)
	at android.os.Parcel.createException(Parcel.java:2422)
	at android.os.Parcel.readException(Parcel.java:2405)
	at android.os.Parcel.readException(Parcel.java:2347)
	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:6848)
	at android.app.ActivityThread.acquireProvider(ActivityThread.java:7849)
	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:3527)
	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2533)
	at android.content.ContentResolver.query(ContentResolver.java:1210)
	at android.content.ContentResolver.query(ContentResolver.java:1158)
	at android.content.ContentResolver.query(ContentResolver.java:1114)
	at com.hiddenramblings.tagmo.amiibo.AmiiboDocument.listFiles(AmiiboDocument.java:81)
	at com.hiddenramblings.tagmo.amiibo.AmiiboDocument.listFiles(AmiiboDocument.java:66)
	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiiboDocuments(AmiiboManager.java:346)
	at com.hiddenramblings.tagmo.browser.BrowserActivity.lambda$loadAmiiboDocuments$44(BrowserActivity.java:1833)
	at com.hiddenramblings.tagmo.browser.BrowserActivity.$r8$lambda$sDbEPDnt6h8qsTHQiZ64Zij5itY(Unknown Source:0)
	at com.hiddenramblings.tagmo.browser.BrowserActivity$$ExternalSyntheticLambda74.run(Unknown Source:6)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ContentProviderHelper.checkAssociationAndPermissionLocked(ContentProviderHelper.java:831)
	at com.android.server.am.ContentProviderHelper.getContentProviderImpl(ContentProviderHelper.java:459)
	at com.android.server.am.ContentProviderHelper.getContentProviderImpl(ContentProviderHelper.java:200)
	at com.android.server.am.ContentProviderHelper.getContentProvider(ContentProviderHelper.java:174)
	at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:7638)
```

### Usage Requirements

- [X] I have read and understood the usage requirements for TagMo

**Comment by AbandonedCart** [comment]
Fixed by https://github.com/HiddenRamblings/TagMo/commit/903fd25a9775a807ef099e492d73f25f0d052894
