### ISSUE TITLE
[Email]: Sep 30, 2022, 2:27 PM PST

### ISSUE THREAD

**Issue by AbandonedCart** [HiddenRamblings/TagMo#582]
```
TagMo - #420566f4
Android O_MR1 (8.1.0)
1.81 GB RAM
Installed by publish

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.hiddenramblings.tagmo.eightbit/com.hiddenramblings.tagmo.browser.BrowserActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.hiddenramblings.tagmo.settings.BrowserSettings.notifyChanges()' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2822)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2900)
at android.app.ActivityThread.-wrap11(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1611)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6651)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.hiddenramblings.tagmo.settings.BrowserSettings.notifyChanges()' on a null object reference
at com.hiddenramblings.tagmo.settings.SettingsFragment.lambda$onImageNetworkChange$16(SettingsFragment.java:281)
at com.hiddenramblings.tagmo.settings.SettingsFragment.$r8$lambda$KLK5yEgNAyek_ip3d_uWj7IRzkc(Unknown Source:0)
at com.hiddenramblings.tagmo.settings.SettingsFragment$$ExternalSyntheticLambda24.run(Unknown Source:2)
at android.app.Activity.runOnUiThread(Activity.java:6203)
at com.hiddenramblings.tagmo.settings.SettingsFragment.onImageNetworkChange(SettingsFragment.java:281)
at com.hiddenramblings.tagmo.settings.SettingsFragment.onCreate(SettingsFragment.java:90)
at androidx.fragment.app.Fragment.performCreate(Fragment.java:3090)
at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:257)
at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1433)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2977)
at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2884)
at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:252)
at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:220)
at com.hiddenramblings.tagmo.browser.BrowserActivity.onCreate(BrowserActivity.java:238)
at android.app.Activity.performCreate(Activity.java:7028)
at android.app.Activity.performCreate(Activity.java:7019)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2775)
... 9 more
```

**Comment by AbandonedCart** [comment]
Fixed as part of https://github.com/HiddenRamblings/TagMo/commit/1fdb77972d295c112e133ef62c1be2dd71ac5b83
