### ISSUE TITLE
[Issue]: tagmo crashed again while I was in the menus 

### ISSUE THREAD

**Issue by sentientmilkshake** [HiddenRamblings/TagMo#590]
### Issue Description

Hello sorry I don't know where the old post is but when I was in the menus just now it crashed again I was just reading the disclaimer about Foomiibo I was not clicking options it made a copy paste report and I have put that below thank you 

### Logcat Output

```shell
TagMo - #2fde3eb
Android TIRAMISU (13)
5.46 GB RAM
Installed by github

com.github.anrwatchdog.ANRError: Application Not Responding for at least 10000 ms.
Caused by: com.github.anrwatchdog.ANRError$$$_Thread: main (state = RUNNABLE)
	at android.graphics.HardwareRenderer.nSyncAndDrawFrame(Native Method)
	at android.graphics.HardwareRenderer.syncAndDrawFrame(HardwareRenderer.java:457)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:804)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4579)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4290)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3517)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2286)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8948)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:832)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

### Usage Requirements

- [X] I have read and understood the usage requirements for TagMo

**Comment by AbandonedCart** [comment]
Looks like it isn't actually including the cause, but it appears to be every time there is an API update available.

**Comment by AbandonedCart** [comment]
It's identical
