### ISSUE TITLE
[Issue]: NFC tag may be corrupt

### ISSUE THREAD

**Issue by AbandonedCart** [HiddenRamblings/TagMo#606]
### Issue Description

Writing to blank tag causes `NFC tag may be corrupt` message

### Logcat Output

```shell
TagMo 3.3.5 (Google Play Release) #ef3781cf 
Android R (11) - 10.07 GB RAM

--------- beginning of main
 11-06 11:46:16.721 6394 6394 W View : requestLayout() improperly called by myinnos.indexfastscrollrecycler.IndexFastScrollRecyclerView{ae33302 VFED.V... ......ID 0,0-1080,24 #7f090083 app:id/browser_content} during layout: running second layout pass 
11-06 11:46:16.780 6394 6394 W View : requestLayout() improperly called by android.widget.LinearLayout{c605f55 V.E..V... ......I. 0,0-1046,215} during second layout pass: posting in next frame 
11-06 11:46:16.780 6394 6394 W View : requestLayout() improperly called by android.widget.LinearLayout{5808f6 V.E..V... ......I. 0,55-808,87 #7f09011a app:id/group1} during second layout pass: posting in next frame 
11-06 11:46:16.780 6394 6394 W View : requestLayout() improperly called by android.widget.LinearLayout{c7af4f7 V.E..V... ......I. 0,87-808,119 #7f09011b app:id/group2} during second layout pass: posting in next frame 
11-06 11:46:16.780 6394 6394 W View : requestLayout() improperly called by android.widget.LinearLayout{778c7c5 V.E..V... ......I. 0,0-1046,215} during second layout pass: posting in next frame 
11-06 11:46:16.780 6394 6394 W View : requestLayout() improperly called by android.widget.LinearLayout{507bf64 V.E..V... ......I. 0,55-808,87 #7f09011a app:id/group1} during second layout pass: posting in next frame 
11-06 11:46:16.780 6394 6394 W View : requestLayout() improperly called by android.widget.LinearLayout{bf525cd V.E..V... ......I. 0,87-808,119 #7f09011b app:id/group2} during second layout pass: posting in next frame 
11-06 11:46:16.780 6394 6394 W View : requestLayout() improperly called by android.widget.LinearLayout{742c35 V.E..V... ......I. 0,0-1046,215} during second layout pass: posting in next frame 
11-06 11:46:16.780 6394 6394 W View : requestLayout() improperly called by android.widget.LinearLayout{273be82 V.E..V... ......I. 0,55-808,87 #7f09011a app:id/group1} during second layout pass: posting in next frame 
11-06 11:46:16.780 6394 6394 W View : requestLayout() improperly called by android.widget.LinearLayout{9dfe993 V.E..V... ......I. 0,87-808,119 #7f09011b app:id/group2} during second layout pass: posting in next frame 
11-06 11:46:16.780 6394 6394 W View : requestLayout() improperly called by android.widget.LinearLayout{4098ca5 V.E..V... ......I. 0,0-1046,215} during second layout pass: posting in next frame 
11-06 11:46:16.780 6394 6394 W View : requestLayout() improperly called by android.widget.LinearLayout{8336dd0 V.E..V... ......ID 0,55-808,87 #7f09011a app:id/group1} during second layout pass: posting in next frame 
11-06 11:46:16.780 6394 6394 W View : requestLayout() improperly called by android.widget.LinearLayout{83b51c9 V.E..V... ......ID 0,87-808,119 #7f09011b app:id/group2} during second layout pass: posting in next frame 
11-06 11:46:35.524 6394 6394 W IInputConnectionWrapper: requestCursorAnchorInfo on inactive InputConnection 
11-06 11:46:37.304 6394 6394 W Choreographer: Frame time is 0.003147 ms in the future! Check that graphics HAL is generating vsync timestamps using the correct timebase. 
11-06 11:46:38.070 6394 6394 W Choreographer: Frame time is 0.111938 ms in the future! Check that graphics HAL is generating vsync timestamps using the correct timebase. 
11-06 11:46:44.858 6394 16910 W NullPointerException: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.hiddenramblings.tagmo.nfctech.NTAG215.connect()' on a null object reference 
11-06 11:46:44.858 6394 16910 W NullPointerException: at com.hiddenramblings.tagmo.NfcActivity.onTagDiscovered(NfcActivity.java:305) 
11-06 11:46:44.858 6394 16910 W NullPointerException: at com.hiddenramblings.tagmo.NfcActivity.lambda$onNewIntent$0(NfcActivity.java:250) 
11-06 11:46:44.858 6394 16910 W NullPointerException: at com.hiddenramblings.tagmo.NfcActivity.$r8$lambda$vP5NXNBqg2kDV8eg_wytd2g-zlQ(Unknown Source:0) 
11-06 11:46:44.858 6394 16910 W NullPointerException: at com.hiddenramblings.tagmo.NfcActivity$$ExternalSyntheticLambda0.run(Unknown Source:4) 
11-06 11:46:44.858 6394 16910 W NullPointerException: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
11-06 11:46:44.858 6394 16910 W NullPointerException: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
11-06 11:46:44.858 6394 16910 W NullPointerException: at java.lang.Thread.run(Thread.java:923)
```

### Usage Requirements

- [X] I have read and understood the usage requirements for TagMo

**Comment by AbandonedCart** [comment]
A while back, the priorities for attempting connections were changed to prevent a false positive fail for the N2 Elite. Since then, the verification for scanning an N2 Elite was drastically improved, but the priorities were never reverted. Restoring them is the major part of the update just pushed to Google Play. It's a bit of a dice roll because I didn't have any tags handy for testing, but it's not new code.

**Comment by AbandonedCart** [comment]
Haven't heard anything further, so my best guess is that this was solved. We can always circle back if it is reported again.
