### ISSUE TITLE
Tagmo crashed

### ISSUE THREAD

**Issue by sentientmilkshake** [HiddenRamblings/TagMo#607]
### Issue Description

Hello I hope you are well tagmo crashed when I opened the menu and scrolled. 

### Logcat Output

```shell
TagMo 3.3.5 (GitHub Release) #977a1e8
Android TIRAMISU (13) - 5.46 GB RAM

android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
	at android.app.ContextImpl.startActivity(ContextImpl.java:1096)
	at android.app.ContextImpl.startActivity(ContextImpl.java:1072)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:432)
	at com.hiddenramblings.tagmo.eightbit.io.Debug.submitLogcat(Debug.java:291)
	at com.hiddenramblings.tagmo.eightbit.io.Debug.processException(Debug.java:304)
	at com.hiddenramblings.tagmo.TagMo.lambda$onCreate$0(TagMo.java:85)
	at com.hiddenramblings.tagmo.TagMo.$r8$lambda$umjGsijGiINgWkG9QZHlZg51_VY(Unknown Source:0)
	at com.hiddenramblings.tagmo.TagMo$$ExternalSyntheticLambda0.onAppNotResponding(Unknown Source:2)
	at com.github.anrwatchdog.ANRWatchDog.run(ANRWatchDog.java:277)
```

### Usage Requirements

- [X] I have read and understood the usage requirements for TagMo

**Comment by AbandonedCart** [comment]
The problems are with Glide and Play Billing. One is already working on it. The other is Google and will get to it if and when they feel like it.
