### ISSUE TITLE
[Issue]:  #7ecdd131 crashes

### ISSUE THREAD

**Issue by yjeanrenaud** [HiddenRamblings/TagMo#658]
### Issue Description

App crashes on N2Elite on updating banks, reading banks or other actions on the device.

### Logcat Output

```shell
TagMo 3.5.2 (Google Play Release) #7ecdd131
Android R (11) - 7.33 GB RAM

java.lang.IllegalStateException: Attempting to launch an unregistered ActivityResultLauncher with contract androidx.activity.result.contract.ActivityResultContracts$StartActivityForResult@100b523 and input Intent { act=com.hiddenramblings.tagmo.eightbit.ACTIVATE_BANK cmp=com.hiddenramblings.tagmo.eightbit/com.hiddenramblings.tagmo.NfcActivity (has extras) }. You must ensure the ActivityResultLauncher is registered before calling launch().
 at androidx.activity.result.ActivityResultRegistry$2.launch(ActivityResultRegistry.java:168)
 at androidx.fragment.app.Fragment$10.launch(Fragment.java:3612)
 at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:47)
 at com.hiddenramblings.tagmo.browser.EliteBankFragment.getAmiiboToolbar$lambda$19(EliteBankFragment.kt:647)
 at com.hiddenramblings.tagmo.browser.EliteBankFragment.$r8$lambda$-hJMNt3jKrJydz9yHtnnB9T277k(Unknown Source:0)
 at com.hiddenramblings.tagmo.browser.EliteBankFragment$$ExternalSyntheticLambda21.onMenuItemClick(Unknown Source:6)
 at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:221)
 at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
 at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:836)
 at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:159)
 at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:987)
 at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:977)
 at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:625)
 at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:156)
 at android.view.View.performClick(View.java:7448)
 at android.view.View.performClickInternal(View.java:7425)
 at android.view.View.access$3600(View.java:810)
 at android.view.View$PerformClick.run(View.java:28309)
 at android.os.Handler.handleCallback(Handler.java:938)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:223)
 at android.app.ActivityThread.main(ActivityThread.java:7715)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
```

### Usage Requirements

- [X] I have read and understood the usage requirements for TagMo

**Comment by AbandonedCart** [comment]
Unfortunately, the only way to fix an issue in a given version would be with an update. This means there is no way to go back to a previous version and fix an issue in place. If the issue still exists in the current version, feel free to update or resubmit the report.
