### ISSUE TITLE
[Issue]: Recent versions of TagMo hang shortly after starting

### ISSUE THREAD

**Issue by Garonne** [HiddenRamblings/TagMo#677]
### Issue Description

I just reinstalled TagMo after not needing it for quite some time. After about 2-3 minutes the app hangs for about 60 seconds and then repeatedly hangs again for a couple of seconds about every minute.

Using a Samsung Galaxy S20 FE Smpartphone

EDIT:  Problems start about a minute after scanning an N2Elite-Chip

### Logcat Output

```shell

TagMo 3.7.9 (GitHub Release) #4c39598
samsung TIRAMISU (13) - 5.00 GB RAM

com.github.anrwatchdog.ANRError: Application Not Responding for at least 20000 ms.
Caused by: com.github.anrwatchdog.ANRError$$$_Thread: main (state = RUNNABLE)
	at android.graphics.HardwareRenderer.nDestroyHardwareResources(Native Method)
	at android.graphics.HardwareRenderer.clearContent(HardwareRenderer.java:540)
	at android.view.ThreadedRenderer.destroyHardwareResources(ThreadedRenderer.java:564)
	at android.view.ViewRootImpl.destroyHardwareRenderer(ViewRootImpl.java:10364)
	at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:6320)
	at android.view.ViewRootImpl.doDie(ViewRootImpl.java:10287)
	at android.view.ViewRootImpl.die(ViewRootImpl.java:10263)
	at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:685)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:621)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:206)
	at android.widget.PopupWindow.dismissImmediate(PopupWindow.java:2371)
	at android.widget.PopupWindow.-$$Nest$mdismissImmediate(Unknown Source:0)
	at android.widget.PopupWindow$3.onTransitionEnd(PopupWindow.java:2301)
	at android.widget.PopupWindow$PopupDecorView.lambda$startExitTransition$0$android-widget-PopupWindow$PopupDecorView(PopupWindow.java:2944)
	at android.widget.PopupWindow$PopupDecorView$$ExternalSyntheticLambda1.run(Unknown Source:8)
	at android.widget.PopupWindow$PopupDecorView$2.onTransitionEnd(PopupWindow.java:2963)
	at android.transition.Transition.end(Transition.java:1926)
	at android.transition.Transition$3.onAnimationEnd(Transition.java:1876)
	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:600)
	at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1333)
	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1575)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:307)
	at android.animation.AnimationHandler.-$$Nest$mdoAnimationFrame(Unknown Source:0)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:86)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1299)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
	at android.view.Choreographer.doCallbacks(Choreographer.java:923)
	at android.view.Choreographer.doFrame(Choreographer.java:847)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: com.github.anrwatchdog.ANRError$$$_Thread: Chrome_ProcessLauncherThread (state = RUNNABLE)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:186)
	at android.os.Looper.loop(Looper.java:313)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.github.anrwatchdog.ANRError$$$_Thread: CleanupReference (state = WAITING)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:442)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:203)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:224)
	at ck.run(chromium-TrichromeWebViewGoogle.aab-stable-561513633:3)
Caused by: com.github.anrwatchdog.ANRError$$$_Thread: ConnectivityThread (state = RUNNABLE)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:186)
	at android.os.Looper.loop(Looper.java:313)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.github.anrwatchdog.ANRError$$$_Thread: DefaultDispatcher-worker-1 (state = TIMED_WAITING)
	at jdk.internal.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:357)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.park(CoroutineScheduler.kt:795)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.tryPark(CoroutineScheduler.kt:740)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:711)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: com.github.anrwatchdog.ANRError$$$_Thread: DefaultDispatcher-worker-2 (state = TIMED_WAITING)
	... 6 more
Caused by: com.github.anrwatchdog.ANRError$$$_Thread: DefaultDispatcher-worker-3 (state = RUNNABLE)
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:662)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:778)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2034)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1849)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1525)
	at com.hiddenramblings.tagmo.nfctech.TagReader.readTagDocument(TagReader.kt:56)
	at com.hiddenramblings.tagmo.nfctech.TagArray.getValidatedDocument(TagArray.kt:324)
	at com.hiddenramblings.tagmo.amiibo.AmiiboManager.listAmiiboDocuments(AmiiboManager.kt:349)
	at com.hiddenramblings.tagmo.browser.BrowserActivity$loadAmiiboDocuments$1.invokeSuspend(BrowserActivity.kt:1822)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	... 1 more
Caused by: com.github.anrwatchdog.ANRError$$$_Thread: DefaultDispatcher-worker-4 (state = RUNNABLE)
	... 18 more
Caused by: com.github.anrwatchdog.ANRError$$$_Thread: DefaultDispatcher-worker-5 (state = TIMED_WAITING)
	at jdk.internal.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:357)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.park(CoroutineScheduler.kt:795)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.tryPark(CoroutineScheduler.kt:740)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:711)
	... 1 more
Caused by: com.github.anrwatchdog.ANRError$$$_Thread: DefaultDispatcher-worker-6 (state = TIMED_WAITING)
	... 6 more
Caused by: com.github.anrwatchdog.ANRError$$$_Thread: DefaultDispatcher-worker-7 (state = TIMED_WAITING)
	... 6 more
Caused by: com.github.anrwatchdog.ANRError$$$_Thread: FinalizerDaemon (state = WAITING)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:442)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:203)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:224)
	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:300)
	at java.lang.Daemons$Daemon.run(Daemons.java:140)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: com.github.anrwatchdog.ANRError$$$_Thread: FinalizerWatchdogDaemon (state = TIMED_WAITING)
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:450)
	at java.lang.Thread.sleep(Thread.java:355)
	at java.lang.Daemons$FinalizerWatchdogDaemon.sleepForNanos(Daemons.java:438)
	at java.lang.Daemons$FinalizerWatchdogDaemon.waitForProgress(Daemons.java:480)
	at java.lang.Daemons$FinalizerWatchdogDaemon.runInternal(Daemons.java:369)
	... 2 more
Caused by: com.github.anrwatchdog.ANRError$$$_Thread: GoogleApiHandler (state = RUNNABLE)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:186)
	at android.os.Looper.loop(Looper.java:313)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.github.anrwatchdog.ANRError$$$_Thread: OkHttp ConnectionPool (state = TIMED_WAITING)
	at java.lang.Object.wait(Native Method)
	at com.android.okhttp.ConnectionPool$1.run(ConnectionPool.java:106)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: com.github.anrwatchdog.ANRError$$$_Thread: Okio Watchdog (state = WAITING)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:442)
	at java.lang.Object.wait(Object.java:568)
	at com.android.okhttp.okio.AsyncTimeout.awaitTimeout(AsyncTimeout.java:313)
	at com.android.okhttp.okio.AsyncTimeout.access$000(AsyncTimeout.java:42)
	at com.android.okhttp.okio.AsyncTimeout$Watchdog.run(AsyncTimeout.java:288)
Caused by: com.github.anrwatchdog.ANRError$$$_Thread: PlatformServiceBridgeHandlerThread (state = RUNNABLE)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:186)
	at android.os.Looper.loop(Looper.java:313)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.github.anrwatchdog.ANRError$$$_Thread: PlayBillingLibrary-1 (state = WAITING)
	at jdk.internal.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1063)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1123)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: com.github.anrwatchdog.ANRError$$$_Thread: PlayBillingLibrary-2 (state = WAITING)
	... 8 more
Caused by: com.github.anrwatchdog.ANRError$$$_Thread: PlayBillingLibrary-3 (state = WAITING)
	... 8 more
Caused by: com.github.anrwatchdog.ANRError$$$_Thread: PlayBillingLibrary-4 (state = WAITING)
	... 8 more
Caused by: com.github.anrwatchdog.ANRError$$$_Thread: PlayBillingLibrary-5 (state = WAITING)
	... 8 more
Caused by: com.github.anrwatchdog.ANRError$$$_Thread: PlayBillingLibrary-6 (state = WAITING)
	... 8 more
Caused by: com.github.anrwatchdog.ANRError$$$_Thread: PlayBillingLibrary-7 (state = WAITING)
	... 8 more
Caused by: com.github.anrwatchdog.ANRError$$$_Thread: PlayBillingLibrary-8 (state = WAITING)
	... 8 more
Caused by: com.github.anrwatchdog.ANRError$$$_Thread: ReferenceQueueDaemon (state = WAITING)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:442)
	at java.lang.Object.wait(Object.java:568)
	at java.lang.Daemons$ReferenceQueueDaemon.runInternal(Daemons.java:232)
	at java.lang.Daemons$Daemon.run(Daemons.java:140)
	... 1 more
Caused by: com.github.anrwatchdog.ANRError$$$_Thread: glide-active-resources (state = WAITING)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:442)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:203)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:224)
	at com.bumptech.glide.load.engine.ActiveResources.cleanReferenceQueue(ActiveResources.java:132)
	at com.bumptech.glide.load.engine.ActiveResources$2.run(ActiveResources.java:61)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at com.bumptech.glide.load.engine.ActiveResources$1$1.run(ActiveResources.java:43)
	... 1 more
Caused by: com.github.anrwatchdog.ANRError$$$_Thread: glide-disk-cache-thread-0 (state = WAITING)
	at jdk.internal.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
	at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:549)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1063)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1123)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:424)
	at java.lang.Thread.run(Thread.java:1012)
	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultPriorityThreadFactory$1.run(GlideExecutor.java:383)
Caused by: com.github.anrwatchdog.ANRError$$$_Thread: glide-source-thread-0 (state = WAITING)
	... 10 more
Caused by: com.github.anrwatchdog.ANRError$$$_Thread: glide-source-thread-1 (state = WAITING)
	... 10 more
Caused by: com.github.anrwatchdog.ANRError$$$_Thread: glide-source-thread-2 (state = WAITING)
	... 10 more
Caused by: com.github.anrwatchdog.ANRError$$$_Thread: glide-source-thread-3 (state = WAITING)
	... 10 more
Caused by: com.github.anrwatchdog.ANRError$$$_Thread: process reaper (state = TIMED_WAITING)
	at jdk.internal.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:463)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:361)
	at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:939)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1062)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1123)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: com.github.anrwatchdog.ANRError$$$_Thread: queued-work-looper (state = RUNNABLE)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:186)
	at android.os.Looper.loop(Looper.java:313)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.github.anrwatchdog.ANRError$$$_Thread: queued-work-looper-data (state = WAITING)
	at jdk.internal.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1063)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1123)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: com.github.anrwatchdog.ANRError$$$_Thread: |ANR-WatchDog| (state = RUNNABLE)
	at dalvik.system.VMStack.getThreadStackTrace(Native Method)
	at java.lang.Thread.getStackTrace(Thread.java:1841)
	at java.lang.Thread.getAllStackTraces(Thread.java:1909)
	at com.github.anrwatchdog.ANRError.New(ANRError.java:83)
	at com.github.anrwatchdog.ANRWatchDog.run(ANRWatchDog.java:286)
```

### Usage Requirements

- [X] I have read and understood the usage requirements for TagMo

**Comment by Garonne** [comment]
Figured out how to find Logcat and added it to the description.
Also probably found N2Elite to be triggering issue.

**Comment by Garonne** [comment]
Actually found two more logcats TagMo automatically copied to clipboard:

May 14th, 5:02 pm:
```shell

TagMo 3.7.9 (GitHub Release) #4c39598
samsung TIRAMISU (13) - 5.00 GB RAM

--------- beginning of main
05-14 16:52:41.194 25962 25991 W Parcel  : Expecting binder but got null!
```

May 14th, 5:04 pm:
```shell

TagMo 3.7.9 (GitHub Release) #4c39598
samsung TIRAMISU (13) - 5.00 GB RAM

--------- beginning of main
05-14 17:02:31.346  1903  1903 W BottomSheetBehavior: Cannot set state: 5
05-14 17:02:31.347  1903  1903 W View    : requestLayout() improperly called by androidx.appcompat.widget.AppCompatTextView{41f96b2 V.ED..... ......ID 216,43-424,124} during layout: running second layout pass
05-14 17:02:31.347  1903  1903 W View    : requestLayout() improperly called by androidx.recyclerview.widget.RecyclerView{2eec8c8 VFED.V... ......ID 0,264-1080,1793 #7f0900db app:id/elite_content} during layout: running second layout pass
05-14 17:02:31.620  1903  3171 W VideoCapabilities: Unsupported mime image/vnd.android.heic
05-14 17:02:31.623  1903  3171 W AudioCapabilities: Unsupported mime audio/x-ape
05-14 17:02:31.624  1903  3171 W AudioCapabilities: Unsupported mime audio/x-ima
05-14 17:02:31.624  1903  3171 W AudioCapabilities: Unsupported mime audio/mpeg-L1
05-14 17:02:31.624  1903  3171 W AudioCapabilities: Unsupported mime audio/mpeg-L2
05-14 17:02:31.624  1903  3171 W VideoCapabilities: Unsupported mime video/mp43
05-14 17:02:31.624  1903  3171 W VideoCapabilities: Unsupported mime video/wvc1
05-14 17:02:31.625  1903  3171 W VideoCapabilities: Unsupported mime video/x-ms-wmv
05-14 17:02:31.625  1903  3171 W AudioCapabilities: Unsupported mime audio/x-ms-wma
05-14 17:02:31.625  1903  3171 W VideoCapabilities: Unsupported mime video/x-ms-wmv7
05-14 17:02:31.625  1903  3171 W VideoCapabilities: Unsupported mime video/x-ms-wmv8
05-14 17:03:17.391  1903  1936 W Parcel  : Expecting binder but got null!
```

Last Logcat (added to the first post) was created shortly after this one.

**Comment by AbandonedCart** [comment]
I'm not entirely sure that ANRWatchdog actually has any value. The N2 page being where it starts is the part that was known, but the exact cause has evaded nearly a full rewrite of the code.

**Comment by AbandonedCart** [comment]
More specifically, the issue appears to be in the bottom drawer of the N2 page.

**Comment by Garonne** [comment]
Any idea when this issue first occured? My very old TagMo 2.7.5 version works fine... It's just unable to identify recent Amiibos (like the new Zelda TotK Amiibo).

**Comment by AbandonedCart** [comment]
If you scan an N2, switch to device options, then swipe the numbers, does it start to lag on the 6th swipe?

**Comment by AbandonedCart** [comment]
As a temporary solution, if "force software layer" is not already enabled in settings, enable it. The number pickers will stop snapping into place, but it will solve the lag.

**Comment by Garonne** [comment]
"Force software layer" didn't fix it. But I still have TagMo 2.7.5 as backup.

Logcat 1:
```shell
TagMo 3.8.4 (GitHub Release) #ad66a2a
samsung TIRAMISU (13) - 5.00 GB RAM

--------- beginning of main
05-22 15:30:12.351 23692 23692 W ziparchive: Unable to open '/data/app/~~N4Ql6ka240-In84vD9BfBA==/com.google.android.trichromelibrary_567213133-tti68dpuNDPVo5Unk1fLzw==/base.dm': No such file or directory
05-22 15:30:12.351 23692 23692 W ziparchive: Unable to open '/data/app/~~N4Ql6ka240-In84vD9BfBA==/com.google.android.trichromelibrary_567213133-tti68dpuNDPVo5Unk1fLzw==/base.dm': No such file or directory
05-22 15:30:12.351 23692 23692 W .tagmo.eightbit: Entry not found
05-22 15:30:12.804 23692 24148 W cr_media: BLUETOOTH_CONNECT permission is missing.
05-22 15:30:12.805 23692 24148 W cr_media: registerBluetoothIntentsIfNeeded: Requires BLUETOOTH permission
05-22 15:30:13.190 23692 24154 W VideoCapabilities: Unsupported mime image/vnd.android.heic
05-22 15:30:13.197 23692 24154 W AudioCapabilities: Unsupported mime audio/x-ape
05-22 15:30:13.197 23692 24154 W AudioCapabilities: Unsupported mime audio/x-ima
05-22 15:30:13.197 23692 24154 W AudioCapabilities: Unsupported mime audio/mpeg-L1
05-22 15:30:13.197 23692 24154 W AudioCapabilities: Unsupported mime audio/mpeg-L2
05-22 15:30:13.197 23692 24154 W VideoCapabilities: Unsupported mime video/mp43
05-22 15:30:13.197 23692 24154 W VideoCapabilities: Unsupported mime video/wvc1
05-22 15:30:13.197 23692 24154 W VideoCapabilities: Unsupported mime video/x-ms-wmv
05-22 15:30:13.198 23692 24154 W AudioCapabilities: Unsupported mime audio/x-ms-wma
05-22 15:30:13.198 23692 24154 W VideoCapabilities: Unsupported mime video/x-ms-wmv7
05-22 15:30:13.198 23692 24154 W VideoCapabilities: Unsupported mime video/x-ms-wmv8
05-22 15:30:42.963 23692 23728 W Parcel  : Expecting binder but got null!
```

Logcat 2:
```shell
TagMo 3.8.4 (GitHub Release) #ad66a2a
samsung TIRAMISU (13) - 5.00 GB RAM

--------- beginning of main
05-22 15:35:19.374 28586 28707 E chromium: [ERROR:simple_file_enumerator.cc(21)] opendir /data/user/0/com.hiddenramblings.tagmo.eightbit/cache/WebView/Default/HTTP Cache/Code Cache/wasm: No such file or directory (2)
05-22 15:35:19.374 28586 28707 E chromium: [ERROR:simple_index_file.cc(614)] Could not reconstruct index from disk
05-22 15:35:19.415 28586 28726 W cr_media: BLUETOOTH_CONNECT permission is missing.
05-22 15:35:19.415 28586 28726 W cr_media: registerBluetoothIntentsIfNeeded: Requires BLUETOOTH permission
05-22 15:35:19.593 28586 28733 W VideoCapabilities: Unsupported mime image/vnd.android.heic
05-22 15:35:19.595 28586 28733 W AudioCapabilities: Unsupported mime audio/x-ape
05-22 15:35:19.595 28586 28733 W AudioCapabilities: Unsupported mime audio/x-ima
05-22 15:35:19.596 28586 28733 W AudioCapabilities: Unsupported mime audio/mpeg-L1
05-22 15:35:19.596 28586 28733 W AudioCapabilities: Unsupported mime audio/mpeg-L2
05-22 15:35:19.596 28586 28733 W VideoCapabilities: Unsupported mime video/mp43
05-22 15:35:19.596 28586 28733 W VideoCapabilities: Unsupported mime video/wvc1
05-22 15:35:19.596 28586 28733 W VideoCapabilities: Unsupported mime video/x-ms-wmv
05-22 15:35:19.596 28586 28733 W AudioCapabilities: Unsupported mime audio/x-ms-wma
05-22 15:35:19.596 28586 28733 W VideoCapabilities: Unsupported mime video/x-ms-wmv7
05-22 15:35:19.596 28586 28733 W VideoCapabilities: Unsupported mime video/x-ms-wmv8
05-22 15:36:12.261 28586 28606 W Parcel  : Expecting binder but got null!
```

**Comment by AbandonedCart** [comment]
2.7.5 isn't really a solution, given the number of changes. It appears your issue is with bluetooth. That's interesting.

**Comment by Garonne** [comment]
Did you remove Flask support between 3.8.4 and 3.9.1? Anyways, 3.9.1 seems to work flawlessly with N2Elite again.

**Comment by AbandonedCart** [comment]
It's labeled "Bluetooth" now because there are multiple devices.

**Comment by Garonne** [comment]
Yep. Found it. It's labeled "Bluetooth-Browser" in my edition. Well. Issue fixed. Nothing more from my side.

**Comment by AbandonedCart** [comment]
The menu button is "Bluetooth Browser" and the page appears as "Bluetooth" but you can get there by either clicking the menu or swiping horizontally. It no longer requires being enabled, since enabling and disabling it had no impact on anything other than the previous tab being visible.
