### ISSUE TITLE
[Logcat]: TagMo #c5278ca

### ISSUE THREAD

**Issue by zenaro147** [HiddenRamblings/TagMo#688]
### Issue Description

Error during write on N2 elite. It can write the bin file, but crash right after finish

### Logcat Output

```shell
TagMo 3.8.4 (GitHub Release) #c5278ca
samsung TIRAMISU (13) - 7.00 GB RAM

android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:11586)
at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:2648)
at android.view.View.requestLayout(View.java:27612)
at android.view.View.requestLayout(View.java:27612)
at android.view.View.requestLayout(View.java:27612)
at android.view.View.requestLayout(View.java:27612)
at android.view.View.requestLayout(View.java:27612)
at android.view.View.requestLayout(View.java:27612)
at androidx.drawerlayout.widget.DrawerLayout.requestLayout(DrawerLayout.java:1353)
at android.view.View.requestLayout(View.java:27612)
at android.view.View.requestLayout(View.java:27612)
at android.view.View.requestLayout(View.java:27612)
at android.view.View.requestLayout(View.java:27612)
at androidx.recyclerview.widget.RecyclerView.requestLayout(RecyclerView.java:4881)
at android.view.View.requestLayout(View.java:27612)
at android.view.View.requestLayout(View.java:27612)
at android.view.View.requestLayout(View.java:27612)
at android.view.View.requestLayout(View.java:27612)
at androidx.recyclerview.widget.RecyclerView.requestLayout(RecyclerView.java:4881)
at androidx.recyclerview.widget.RecyclerView$RecyclerViewDataObserver.triggerUpdateProcessor(RecyclerView.java:6060)
at androidx.recyclerview.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeChanged(RecyclerView.java:6027)
at androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyItemRangeChanged(RecyclerView.java:13128)
at androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyItemRangeChanged(RecyclerView.java:13118)
at androidx.recyclerview.widget.RecyclerView$Adapter.notifyItemChanged(RecyclerView.java:8023)
at com.hiddenramblings.tagmo.browser.fragment.EliteBankFragment$updateEliteAdapter$1.invokeSuspend(EliteBankFragment.kt:411)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@dfa057a, Dispatchers.IO]
```

### Use Authorizations

- [X] I am authorized to submit this issue by TagMo collaborators

**Comment by trowgundam** [comment]
I got what appears to be the same error, but when trying to connect to a bluup labs Flask. I can confirm that the bluup Connect app is able to connect to and interact with my Flask, and I was able to use the app with my N2 Elite, but I only really use it to activate a specific bank and have not tried adding anything to it however. One time it just sit and "hang" (the animation was playing but never got anywhere) connecting to the Flask, but every othertime it would go "Connectiong" for like a second or two then immediately crash.

Here is my Logcat:
TagMo 3.8.3 (Play Release) #d07057e2
samsung TIRAMISU (13) - 10.00 GB RAM

android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:11586)
at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:2648)
at android.view.View.requestLayout(View.java:27612)
at android.view.View.requestLayout(View.java:27612)
at android.view.View.requestLayout(View.java:27612)
at android.view.View.requestLayout(View.java:27612)
at android.view.View.requestLayout(View.java:27612)
at android.view.View.requestLayout(View.java:27612)
at androidx.drawerlayout.widget.DrawerLayout.requestLayout(DrawerLayout.java:1353)
at android.view.View.requestLayout(View.java:27612)
at android.view.View.requestLayout(View.java:27612)
at android.view.View.requestLayout(View.java:27612)
at android.view.View.requestLayout(View.java:27612)
at androidx.recyclerview.widget.RecyclerView.requestLayout(RecyclerView.java:4881)
at android.view.View.requestLayout(View.java:27612)
at android.view.View.requestLayout(View.java:27612)
at android.view.View.requestLayout(View.java:27612)
at android.view.View.requestLayout(View.java:27612)
at androidx.recyclerview.widget.RecyclerView.requestLayout(RecyclerView.java:4881)
at androidx.recyclerview.widget.RecyclerView.setAdapter(RecyclerView.java:1227)
at com.hiddenramblings.tagmo.browser.fragment.FlaskSlotFragment$flaskServerConn$1$onServiceConnected$1$1$onFlaskListRetrieved$1.invokeSuspend(FlaskSlotFragment.kt:184)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@68289f9, Dispatchers.IO]
