### ISSUE TITLE
Failed to decrypt tag data with Foomiibo panel

### ISSUE THREAD

**Issue by wzhy90** [HiddenRamblings/TagMo#700]
Log as below, but it works with files in "build  foomiibo"
```
00-00 00:00:00.000  1000 20000 W Exception: java.lang.Exception: Failed to decrypt tag data
00-00 00:00:00.000  1000 20000 W Exception: at com.hiddenramblings.tagmo.amiibo.KeyManager.decrypt(KeyManager.kt:111)
00-00 00:00:00.000  1000 20000 W Exception: at com.hiddenramblings.tagmo.nfctech.TagWriter.writeToTagAuto(TagWriter.kt:105)
00-00 00:00:00.000  1000 20000 W Exception: at com.hiddenramblings.tagmo.nfctech.NfcActivity$onTagDiscovered$2.invokeSuspend(NfcActivity.kt:299)
00-00 00:00:00.000  1000 20000 W Exception: at com.hiddenramblings.tagmo.nfctech.NfcActivity$onTagDiscovered$2.invoke(NfcActivity.kt:0)
00-00 00:00:00.000  1000 20000 W Exception: at com.hiddenramblings.tagmo.nfctech.NfcActivity$onTagDiscovered$2.invoke(NfcActivity.kt:0)
00-00 00:00:00.000  1000 20000 W Exception: at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
00-00 00:00:00.000  1000 20000 W Exception: at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
00-00 00:00:00.000  1000 20000 W Exception: at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
00-00 00:00:00.000  1000 20000 W Exception: at com.hiddenramblings.tagmo.nfctech.NfcActivity.onTagDiscovered(NfcActivity.kt:218)
00-00 00:00:00.000  1000 20000 W Exception: at com.hiddenramblings.tagmo.nfctech.NfcActivity.access$onTagDiscovered(NfcActivity.kt:47)
00-00 00:00:00.000  1000 20000 W Exception: at com.hiddenramblings.tagmo.nfctech.NfcActivity$onNewIntent$1.invokeSuspend(NfcActivity.kt:702)
00-00 00:00:00.000  1000 20000 W Exception: at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
00-00 00:00:00.000  1000 20000 W Exception: at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
00-00 00:00:00.000  1000 20000 W Exception: at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
00-00 00:00:00.000  1000 20000 W Exception: at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
00-00 00:00:00.000  1000 20000 W Exception: at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
00-00 00:00:00.000  1000 20000 W Exception: at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
00-00 00:00:00.000  1000 20000 W Exception: at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
00-00 00:00:00.000  1000 20000 W Exception: at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by AbandonedCart** [comment]
Fixed by https://github.com/HiddenRamblings/TagMo/commit/093066a0b89938b0624f86fdde54aaaf40a42b06
