### ISSUE TITLE
[Issue]: Tagmo does not go beyond the menu screen and closes.

### ISSUE THREAD

**Issue by Vorffeed** [HiddenRamblings/TagMo#726]
### Issue Description

I have updated to this latest version and the program does not go beyond the initial menu, and closes automatically, and does not allow access to menu the amiibo or even to the three dots menu to hit report problem.

### Logcat Output

```shell
TagMo 4.1.4-wear (GitHub Wear OS) #9d7409a
Xiaomi S (12) - 5.00 GB RAM

java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.wear.widget.drawer.WearableDrawerController.closeDrawer()' on a null object reference
    at androidx.wear.widget.drawer.WearableNavigationDrawerView$1.run(WearableNavigationDrawerView.java:105)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:210)
    at android.os.Looper.loop(Looper.java:299)
    at android.app.ActivityThread.main(ActivityThread.java:8319)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
```

### Usage Requirements

- [X] I have read and understood the usage requirements for TagMo

**Comment by AbandonedCart** [comment]
You're using the Wear OS version on a phone. Make sure to install the regular Android version.
